= 5.x リリースノート
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /releasenotes/5x

== 5.xのリリースノート

[NOTE]
====
新しいリリースのお知らせをメールで受け取るには、このSUSEメーリングリストにご登録ください： https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 2025年8月

==== 新機能

* *NVSHAS-6733*:応答ルールをCRDとしてエクスポートする。
* *NVSHAS-9899*：NeuVectorプロセスプロファイルアラート（Javaサービス用）には機密データが含まれています。
* *NVSHAS-9990*：ユーザーパスワードに新しいハッシュアルゴリズムを採用。
* *NVSHAS-9968*：管理者アカウントのデフォルトパスワードの設定をサポート。

==== バグ修正

* *NVSHAS-10062*：1回目のログイン時に管理者パスワードの作成に失敗し、ManagerにERRORが表示されない。
* *NVSHAS-10041*：ConfigMapを使用してフェデレーションを構成すると、「無効なデータです」と表示され、フェデレーション操作に失敗しました。
* *NVSHAS-10018*：NeuvectorはGitLabレジストリのすべての画像をスキャンしているわけではありません。
* *NVSHAS-10017*：許可されたプロセスに関する誤検出のセキュリティ警告。
* *NVSHAS-10001*：保護/監視の強制は、グループ削除後も「残る」。
* *NVSHAS-9985*：   NeuVector（フェドマスター）は、外部からのすべてのリクエストに対して問題を起こす。
* *NVSHAS-9981*：   セキュリティイベントは、グループ内に新しい「プロセスプロファイルルール」が追加または変更されるたびに発生します。

==== セキュリティ情報

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[管理者アカウントのデフォルトパスワードが安全でない]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[安全でないパスワード管理はレインボー攻撃に弱い]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[デリケートな引数を使った処理は漏洩につながる]

詳しくはxref:cve.adoc[セキュリティ勧告とCVEsの]ドキュメントをご覧ください。

=== 5.4.5 2025年7月

==== 新機能

* *NVSHAS-9776*：ヘルムチャートにetcdの許容範囲を追加。

==== バグ修正

* *NVSHAS-9507*：OCIコンテナがスキャンされない。
* *NVSHAS-9787*：不要なマネージャーログを削除する。
* *NVSHAS-9788*：証明書を生成するアルゴリズムを改良する。
* *NVSHAS-9789*：リモートレジストリ設定の不要なマネージャーログを削除。
* *NVSHAS-9867*：NeuVectorによると、`.NET Library System.Formats.Asn1 v8.013` 、CVE 2024-38095の影響を受けている。
* *NVSHAS-9883*：[quay.io] Docker レジストリでワイルドカードフィルタが動作しない。
* *NVSHAS-9911*：REST APIを使用してリポジトリをスキャンすると、不正な「メッセージ」が表示されます。
* *NVSHAS-9930*：`glibc/libc-bin : 2.36-9+deb12u10` の CVE-2018-20796 - 偽陽性。
* *NVSHAS-9933*：レジストリ・アダプター機能（ハーバー）により、スキャン中にターゲット・レジストリのエラーが表示される。
* *NVSHAS-9934*：ゼロドリフト機能故障の疑い。
* *NVSHAS-9940*：NVスキャンJFrogサブドメインモードの問題。
* *NVSHAS-9942*：顧客画像のイメージスキャンに失敗している。
* *NVSHAS-9945*：プロセス名が長すぎると、適切なプロセス・プロファイル・ルールを作成する方法を判断するのが難しくなります。
* *NVSHAS-9946*：クレデンシャルタイプに対するアドミッションコントロール警告の表示に関する問題。
* *NVSHAS-9947*：[UI-ext] Rancher のコンプライアンスチャートに "Manual" のステータスがない NeuVector.
* *NVSHAS-9948*：`5.4.3` にアップグレードした後、NeuVectorの設定が失われました。
* *NVSHAS-9949*：[Harbor][不正なユーザー名/パスワード]不正なユーザー名/パスワードが入力されていても画像をスキャンしてしまう。
* *NVSHAS-9952*：NVがライセンスキーを発行/チェックしなくなったため、使用状況レポートから「署名」を削除。
* *NVSHAS-9953*：Pods Enforcerが再起動し続ける。
* *NVSHAS-9954*：NeuVector Prometheus エクスポーターが重複したメトリクスを生成する。
* *NVSHAS-9958*：ネットワークのルール実施には時間がかかる。
* *NVSHAS-9960*:スキャナーが作動しない。
* *NVSHAS-9969*：致命的なエラー：マップの同時書き込みにより、Enforcer コンポーネントが再起動します。
* *NVSHAS-9971*：`Get Bootstrap Password` についてのNV UI 。
* *NVSHAS-9975*: [Manager] TypeError:`this.mousemoveListener` は NV GUI で観測された関数ではありません。
* *NVSHAS-9986*:Federated ポリシーのグループビューで、プロセスとファイルのアクセスルールを編集または削除できない。
* *NVSHAS-9988*：UI：2,000以上のグループが存在する場合、グループページにすべてのグループが表示されない。
* *NVSHAS-9991*：グループ`nv.gatekeeper-controller-manager.openshift-azure-guardrails` がUIから消えている。
* *NVSHAS-9993*：MD5をSHA256に置き換える。
* *NVSHAS-9994*：エンフォーサーポッドが再起動し続ける。
* *NVSHAS-9996*：ヘルムチャートは、エンフォーサーポッドの非特権モードを許可すべきである。
* *NVSHAS-9998*：NeuVector連携マスタからグループをエクスポートできません。
* *NVSHAS-10000*：NVをBCI 15.7にアップグレードする。
* *NVSHAS-10003*：Rancher UIが開いている間、スタンドアロンのNVページでページのリロードが機能しない。
* *NVSHAS-10008*：レジストリ スキャン - スキャンした画像の表示メニューが壊れている。
* *NVSHAS-10010*：TCP SYNフラッドがイングレスをブロックし、その結果、イングレス・トラフィックが完全にブロックされる。

=== 5.4.4 2025年5月

==== 新機能

* **NVSHAS-9915**：ハーバースキャナーモジュールのスキャン結果をNeuVector UIに表示します。
* **NVSHAS-9904**：各コンポーネントについて、`imagePullPolicy` を`values.yaml` に公開する。
* **NVSHAS-9869**：UI：DDoS コントロールをグループペインに移動します。
* **NVSHAS-9840**：[GCP] NeuVectorがGCPのオートパイロットをサポート。
* **NVSHAS-9248**：未使用のプロセス/ネットワークルールを、カウンターと`Last Used` タイムスタンプと共に表示する。
* **NVSHAS-8160**: [Controller] セキュリティリスクスコア計算のいくつかの項目を調整しました。
* **NVSHAS-4673**：グループをエクスポートする前にメッセージを追加することを提案。

==== バグ修正

* **NVSHAS-9931**：マルチクラスタでNeuVector製品のバージョンが不一致の場合に警告を表示するようにした。
* **NVSHAS-9925**：`/v1/scan/asset/images` レジストリページのAPIが失敗する。
* **NVSHAS-9913**：ワークロード:XYZグループに関連する複数のネットワークルールの削除に関する問題。
* **NVSHAS-9912**：コントローラのサービスアカウントが必要とするK8のRBACパーミッションについて、Helmを更新します。
* **NVSHAS-9909**：NeuVector Rancher NavLink使用時に「Signed Out - Go to Loading page」のメッセージが表示される。
* **NVSHAS-9898**：連合環境では、顧客が作成したfed.*グループ（例：fed.core-systems）の条件を変更しても機能しない。
* **NVSHAS-9894**：[Enforcer]`Nv.protect` は、コントローラの準備完了プローブコマンド`cat /tmp/ready` を拒否します。
* **NVSHAS-9886**：ネットワークアクティビティで、カスタム外部グループ接続のドメイン名が解決されない。
* **NVSHAS-9884**：[ノードスキャン][コンテナスキャン] スキャンに失敗します。
* **NVSHAS-9873**：NeuVector 5.4.2のUIアドバンスドフィルタ検索の問題。
* **NVSHAS-9865**：エクスポートされるネットワークポリシーは、選択順（選択されたグループが同じ）によって異なります。
* **NVSHAS-9828**: [Enforcer: process] NeuVector Enforcerは短命のポッド（5秒未満のもの）を検出できません。
* **NVSHAS-9783**:icmp パケットを拒否するネットワークポリシーを追加した後、NeuVector は`Security Events` にアラートを表示しない。
* **NVSHAS-9176**：ネームスペース`rt_scan:w` ロールを持つユーザー権限がログインしている場合、[**セキュリティリスク] > [脆弱性]**ページにスクリプトエラーを表示するようになりました。

=== 5.4.3 2025年3月

==== 新機能

* **NVSHAS-9793**：NeuVectorのデプロイ時にConfigMapとSecretを利用してLDAP/userinitcfgでFed Globalロールを許可するようにしました。
* **NVSHAS-9764**: [RFE] Azureの「リモートリポジトリ構成」のサポートを追加しました。
* **NVSHAS-9759**：Ingress-Exposureレポートに日付の詳細を追加する。
* **NVSHAS-9755**：シークレットに関するアラートで、環境変数名を値と一緒に表示するようリクエスト。
* **NVSHAS-9748**: [Helm] NeuVector HelmがCRDの共通グループの名前参照をサポートするように更新されました (NVSHAS0-4717).
* **NVSHAS-9426**：HelmチャートにスキャナーのhostPathを追加。
* **NVSHAS-9326**：NeuVector - Harbor プラガブルスキャナモジュール。
* **NVSHAS-9835**：ノードの自動スキャンを無効にするUI。
* **NVSHAS-7997**：ghcr.io 用スキャナ・コネクタ。
* **NVSHAS-7982**：フェデレーションマスターからWAFセンサーを割り当てる。

==== バグ修正

* **NVSHAS-9849**：エンフォーサーがコントローラーに登録されていない。
* **NVSHAS-9847**：ワイルドカードフィルタがDockerレジストリで機能しない。
* **NVSHAS-9833**：Rancherのデプロイメントで設定のリストアが失敗する。
* **NVSHAS-9832**：ワークロードグループを使用したネットワークルールの作成に関する問題。
* **NVSHAS-9821**：プロセスプロフィットルールアラートのコマンドラインからプロセス名が一致しない。
* **NVSHAS-9817**：NvClusterSecurityRuleのCRDを作成すると、作成に成功したと表示されますが、プロセスルールのエントリが重複しているため、実際には作成されていません。
* **NVSHAS-9812**：NeuVectorのprometheus-exporterのメトリクスがおかしい。
* **NVSHAS-9811**：[Manager] ルートCAと中間CAをシークレットに持つカスタム証明書(CA)を使用するとGUIにアクセスできない
* **NVSHAS-9801**：FIPS モード +`manager.env.ssl=false` 、Manager がエラーになる。
* **NVSHAS-9792**：ボディサイズがConsulの最大値を超えたため、フェデレーションポリシーの同期に失敗しました。
* **NVSHAS-9784**：Jfrog画像リポジトリスキャン中にNeuVectorが404を返した。
* **NVSHAS-9783**:icmpパケットを拒否するネットワークポリシーを追加した後、「セキュリティイベント」にアラートが表示されなくなった。
* **NVSHAS-9780**:NeuVectorのシングルサインオンがRancher NavLinkで動作しない。
* **NVSHAS-9777**：重複した "level" キーを持つ Webhook JSON。
* **NVSHAS-9770**：ゼロ・ドリフト・モード後の自動切り替えは、誤ったポリシーに切り替わる。
* **NVSHAS-9765**：プロテクトモードでは、ファイルへのアクセスは完全にブロックされない。
* **NVSHAS-9756**：EnforcerがCPUの最大値に達し、Memory Pressureの警告がいくつか出た。
* **NVSHAS-9668**:RKE2でコンプライアンス・テストに失敗。
* **NVSHAS-9265**：PRE PCI 環境における脆弱性スキャンの結果が不完全で不正確である。
* **NVSHAS-9227**：レジストリスキャンがスキャンの途中で止まってしまい、"アイドル "状態になる。
* **NVSHAS-9729**：名前空間が「同じ名前」のステートフルセットがプロジェクトに複数配置されている場合に、脆弱性の数が正しくカウントされないという問題がありました。
* **NVSHAS-9810**：NeuVectorコントローラが応答せず、UIにアクセスできない。

=== 5.4.2 2025年1月

==== 新機能

* **NVSHAS-9726**：モニターはプロキシURLを通過するようになった。
* **NVSHAS-9719**：内蔵された証明書の引退を発表。
* **NVSHAS-9715**：Helm Chartの値がコントローラとマネージャのノードポートの設定に対応。
* **NVSHAS-9710**：**脆弱性**タブにソート可能な`feed_rating` 列を含める。
* **NVSHAS-9669**：REST APIによる総合的なセキュリティスコア。
* **NVSHAS-9590**：すべての資産に対してどの脆弱性スコアを適用するかを選択する機能。
* **NVSHAS-7555**：セキュリティ・イベント]に[自動更新]オプションを含める。

==== バグ修正

* **NVSHAS-9662**：Helm chart 2.8.2におけるRole/RoleBindingロジックの不整合。
* **NVSHAS-9652**：splunk の syslog フォーマットの違いを観察した。
* **NVSHAS-9649**：コンテナ・リンクがsecurity-eventで404レスポンス・コードを生成する。
* **NVSHAS-9613**：NeuVector Managerポッドエラー / NeuVector Web UIが使用できません。
* **NVSHAS-9507**：OCIコンテナがスキャンされない。
* **NVSHAS-9443**：leases.coordination.k8s.ioオブジェクトを作成できないため、ArgoCDによるアップグレード/インストールに失敗しました。
* **NVSHAS-9436**：CVE-2024-7347 に対して CVE 偽陰性の可能性。
* **NVSHAS-8386**：秘密鍵と自己署名証明書は依然として複数のイメージで出荷されている。
* **NVSHAS-9754**: [UI] Rancher が SSO ユーザが OpenShift または Rancher の RBAC の認証を無効にするのを防ぐ。
* **NVSHAS-9751**: [Runtime Protection] Monitor Mode + Zero Drift は、子プロセスが実行されたときに警告を生成しません。
* **NVSHAS-9721**：ユーザーが間違ったレジストリ名を入力した場合、UIは適切なエラーメッセージをポップアップする必要があります。
* **NVSHAS-9696**：脆弱性ページにおけるアセットの色表示に一貫性がない。
* **NVSHAS-9686**:Neuvector Helm チャート内のレジストリ・アダプタ証明書のハードコードされた名前空間。
* **NVSHAS-9678**：リンター変更後に過度のエラートレースが発生する。
* **NVSHAS-9670**:マネージャーsbt実行時のプレーンテキストレスポンスの二重引用符の問題と、javaの無名ライブラリの問題。
* **NVSHAS-9667**：コントローラのデプロイメントで、`CTRL_PATH_DEBUG` 環境変数をエラーに設定しても動作しません。
* **NVSHAS-9665**：ファイルアクセスルール：定義済みのルールを削除すると、"setRowData "エラーが発生します。
* **NVSHAS-9664**：政策グループ：カスタム・スクリプトを削除すると "setRowData" が生成されます。

[NOTE]
====
マネージャとレジストアダプタサービスのデフォルトのタイプがClusterIPに変更されました。 NodePortが優先される場合、ユーザーは`manager.svc.type` 、`cve.adapter.svc.type` 、設定をオーバーライドすることができる。
====

NeuVector 5.4.2リリースでは、内蔵証明書を使用したデプロイのサポートを終了しました。NeuVector 5.4.2コンテナイメージ内の`/etc/neuvector/certs/internal` にある証明書は削除されます。NeuVectorの使用を継続するためには、ユーザーは次のことを行う必要があります：

==== 5.4.2 新規設置：

===== ヘルムを使って

- Helmチャートの`internal.autoGenerateCert` 、`internal.autoRotateCert` フラグを有効にします（5.4.2リリースからデフォルトで有効になります）。あるいは、YAMLメソッドが以下にリンクされている。

===== YAMLを使う：

- xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[既存の方法で内部証明書を]提供する。

==== 旧バージョンから5.4.2へのアップグレード：

データを失うことなくローリングアップデートを行うには、コントローラ、エンフォース、レジストリ・アダプタの内部証明書をスキャナから作成し、設定してください。アップグレードする前に、設定のバックアップを取ることをお勧めします。

次の手順は、配置で`.yaml` ファイルを使用する場合にのみ必要です。Helmを使用したアップグレードでは、以下のフラグによって内部証明書がデフォルトで作成されるため、これらの追加手順は必要ありません：`internal.autoGenerateCert` および`internal.autoRotateCert` 。

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

内部証明書が設定されたサンプル 5.4.2 yaml：*https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml*

xref:internal.adoc[内部証明書に関する]追加情報。


PVCコンフィギュレーションの場合、ユーザーは新しいインストールで既存のPVCをコンフィギュレーションして、コンフィギュレーションを復元することができる。


**スキャナーに関する補足事項：**

現在5.4.2より前のバージョンを使用しているユーザーは、2025年3月31日まで`neuvector/scanner:latest` 。それ以降は削除される。ユーザは、スキャナの使用を継続するために、コントローラ、エンフォースメント、スキャナ、およびレジストアダプタに同じ内部証明書を提供することを計画すべきである。

スタンドアロン・スキャナーはこれらの変更の影響を受けませんのでご注意ください。

=== 5.4.1 2024年11月

==== 新機能

* **NVSHAS-8583**：ルールセットにきめ細かなポリシーモードを設定し、グループごとにネットワークポリシーモードとプロファイルモードを分ける。
* **NVSHAS-9440**：CRDでネットワークモードとプロセス・ファイルモードの分離をサポート。
* **NVSHAS-9369**：コントローラのhelmデプロイメントサポートによるデバッグログカテゴリの追加。
* **NVSHAS-9040**：モニターモードでアドミッション・コントロール・ルールが拒否された場合のsyslogメッセージを改善しました。

==== バグ修正

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar はどの vul でも検出できません (以前のスキャナのビルドでは検出できます)。
* **NVSHAS-9447**：コントローラ/スキャナポッドがクラッシュする - "Unsupported system Exit"（サポートされていないシステム終了）。
* **NVSHAS-9278**：最新のスキャナーイメージにCVE-2024-41110が見つかった。
* **NVSHAS-9467**：ポッドラベルで定義されたカスタムグループは、そのプロファイルデータを子コンテナに伝搬しません。
* **NVSHAS-9442**：ArgoCD での展開の問題。
* **NVSHAS-9436**：CVE-2024-7347 に対して CVE 偽陰性の可能性。
* **NVSHAS-9468**：jwt-go を jwt:v5 に置き換えるため、CVE-2020-26160 を修正。
* **NVSHAS-9517**：アドミッション・コントロールに一貫性がなく、誤った結果が出る。
* **NVSHAS-9532**：イメージスキャンは完了しましたが、まだ展開が許可されていません。
* **NVSHAS-9558**：JWT トークンの期限切れレポート http.StatusRequestTimeout 408.
* **NVSHAS-9576**：ユーザーがJenkinsでコントローラモードを使用してスキャンする場合、レジストリデータのパスワードフィールドをクリアする。
* **NVSHAS-9425**：コンテナにvxlanがある場合、nfqを作成する。
* **NVSHAS-9571**: [Registries] すべてのスキャン画像に対するフィルタがうまく動作しない。
* **NVSHAS-9589**：管理クラスタが切断されました - プライマリクラスタとのバージョンの不一致。
* **NVSHAS-8824**：ユーザが自分のグループを削除できず、名前空間スコープのグループを作成できない。
* **NVSHAS-9605**：無効なポリシーモードとプロセスプロファイルモードの値を持つエクスポートグループが誤って許可される。
* **NVSHAS-9608**：スキャナは、コントローラが巨大なスキャン結果～23MBのエラーを報告しても、エラーを報告しない。
* **NVSHAS-9534**：入場コントロールの表示エラー。
* **NVSHAS-9600**：コントローラのデバッグを無効にできない。
* **NVSHAS-9631**：エンフォーサーのミスを減らす。
* **NVSHAS-9645**：既存のCRD処理に失敗。
* **NVSHAS-9592**：新しいDBバージョンにもかかわらず、新しいスキャンがない。
* **NVSHAS-9212**：GET(/v1/eula)でneuvector-binding-secretロール(バインディング)が正しくない場合に警告メッセージを表示する。
* **NVSHAS-9367**：レジストリの接続に失敗した場合のエラーメッセージを強化。
* **NVSHAS-9475**：メニューが折りたたまれているとき、背景のグリッド印刷が完全に覆われない。
* **NVSHAS-9485**：UIの「ネットワークセキュリティポリシーモード」のメッセージが正しくない。
* **NVSHAS-9480**：Rancher ダウンストリームクラスタにデプロイされた NV UI が、Rancher ログアウト後に HTTP/403 をスローします。
* **NVSHAS-9547**：セキュリティリスク--> 脆弱性の表でソートが壊れている。
* **NVSHAS-9570**: [脆弱性] アセットの異なるステータスの凡例の説明を変更してください。
* **NVSHAS-9561**：ダッシュボードボードの総合セキュリティスコアは、実際のスコアと一致すべきである。
* **NVSHAS-9572**: [脆弱性] ユーザがページを更新または再ログインしても、フィルタリングされたデータが保持される。
* **NVSHAS-9597**：コントローラがPOST(v1/group)に対して403を返した場合、UIはエラーに応答しません。
* **NVSHAS-8682**：CRD webhookサービスをcrd helm chartからapplication helm chartに移動する必要があります。

==== 既知の問題

* 2.8.3チャート・リリースでは、これまで誤って割り当てられていたリソースをcrdからcoreに移動しました。crdとコア・チャートの両方を使用している場合、コアを先にデプロイすると、アップグレード中に問題が発生する可能性があります。これを解決するには、まずcrdをアップグレードし、次にコアチャートをアップグレードする。

=== 5.4 2024年9月

* **UIの改善**：
** Rancher SSOユーザーを表示する。
** JWTトークンを管理する。
** 画像ナビゲーションの強化、スキャン結果のリンク。
* **セキュリティの強化**：
** 新しいコンプライアンス・フィルター
** CISベンチマーク、OCIイメージ署名をサポート。
* **ネットワークとモニタリング**
** 高度な帯域幅とセッションのトラッキング
** DDoS監視。
** マルチネットワーク対応。
* **認証管理**：
** ローテーション機能を含む、期限切れ内部証明書に関する新しい通知。
* **自動化と統合**：
** 連盟の自動化。
** Rancher RBACの統合。
** アドミッション・コントロールの改善。
* **パフォーマンスと効率**：
** メモリ使用量の削減。
** ISPのデータ料金引き下げ。
** スキャナのキャッシュ統計の暴露。
* **ユーザビリティの向上**：
** ブートストラップパスワードのサポート。
** クラウド請求データのアーカイブ。
** 名前空間境界の強制。

==== 新機能

* **NVSHAS-9012**：同じユーザー名を持つRancher SSOユーザーをNV UIに表示する。
* **NVSHAS-8939**：Rancher SSO セッションのユーザーが現在の JWT トークンを削除（つまりログアウト）できるように、NV UI にオプションを提供します。
* **NVSHAS-7522**：レジストリの簡単なイメージナビゲーション。
* **NVSHAS-8148**：コンテナイメージからレジストリイメージのスキャン結果へのリンク。
* **NVSHAS-9258**:期限切れ証明書と内部証明書の新しい通知を追加。
* **NVSHAS-8915**：新しいコンプライアンス・フィルターとコンプライアンス・レポートをサポート。
* **NVSHAS-9403**：ファイルモニター-UI：定義済みのファイル監視ルールを削除できるようにする。
* **NVSHAS-8423**：設定されたしきい値に基づいて、グループレベルの帯域幅、アクティブセッション数、およびセッションレート違反を検出します。
* **NVSHAS-9218**：DDoS監視のための連邦政府およびCRDグループのサポート。
* **NVSHAS-8461**：クラウド上のマネージドk8sサービスのCISベンチマークをサポートします。
* **NVSHAS-7664**：レジストリスキャン時のISPデータ通信料を削減。
* **NVSHAS-8868**：スキャナキャッシュの統計情報を公開する。
* **NVSHAS-8676**：ベンチマークスクリプトの NV プロテクトの改善。
* **NVSHAS-9255**：FQDNを持たない画像名のためのアドミッションコントロール検索レジストリをカスタマイズする。
* **NVSHAS-9144**：脆弱性プロファイルにIDを追加し、識別しやすくした。
* **NVSHAS-7687**：CLIからエンフォーサーとコントローラーのログレベル（debug/error/info/warn）を設定できるようになりました。
* **NVSHAS-7518**：{product-name} コンポーネントの内部証明書を変更する。
* **NVSHAS-9287**:内旋を可能にする。
* **NVSHAS-8562**：内部証明書の期限切れ通知を追加。
* **NVSHAS-8486**：Multusネットワークインターフェースをサポート。
* **NVSHAS-7447**：Rancher RBACと{product-name} の統合。
* **NVSHAS-7822**：APIコールをスクリプト化することなく、フェデレーションの自動化を実現。
* **NVSHAS-8799**：コンプライアンス テンプレートをインポートするためのコンプライアンス フレームワークを作成します。
* **NVSHAS-8773**：初期デプロイ時のブートストラップパスワードのサポート。
* **NVSHAS-6740**：プロテクトモードで学習済みリストを強制することにより、ゼロドリフト・ベースライン・プロファイルを改善。
* **NVSHAS-8325**：ネットワークルールのコンテナ名前空間境界を強制する。
* **NVSHAS-8723**：クラウドの課金データをアーカイブする。
* **NVSHAS-9086**:vulTraitデータ構造を排除することで、コントローラプロセスのメモリ使用量を削減。
* **NVSHAS-6979**：応答ルールのコメントをアラートコンテンツに含める機能。
* **NVSHAS-8845**：FedReaderとFedAdminのロールを持つAPIKEYを作成する。
* **NVSHAS-9306**：アドミッション・コントロールの構成評価では、デプロイメントを許可または拒否したルールIDが表示される。
* **NVSHAS-9078**：OCIイメージのイメージ署名をサポート。
* **NVSHAS-7945**：KubernetesのDISA STIGベンチマークをサポートする。
* **NVSHAS-8234**：アドミッション・コントロール 拒否されるべき画像を許可するロジック。

==== バグ修正

* **NVSHAS-9005**：レジストリの TypeError：未定義のプロパティを読み取れません（'total_records'を読み取ります）。
* **NVSHAS-9085**：Assets View PDF レポートでは、現在の脆弱性があっても脆弱性は0%である。
* **NVSHAS-9084**：資産ビュー PDF レポートで、画像リストが空のときに NaN が表示される。
* **NVSHAS-9128**：セキュリティ・イベント：ワークロードの名前空間の値がない場合、コンテナは表示できません。
* **NVSHAS-9025**：コンテナに対するNeuvectorの脆弱性の受け入れ範囲。
* **NVSHAS-9155**：レジストリスキャンイメージの列名に誤りがあり、ファイル名が見つからない
* **NVSHAS-9122**：RancherのSSOログインで "Multiple Cluster "を使用すると、Neuvectorマスターがいつでもログアウトする。
* **NVSHAS-9266**：レジストリのスキャンScan Report by Layer」ボタンは、脆弱性がない場合は非表示または無効にしてください。
* **NVSHAS-9219**：ユーザが認証サーバの証明書検証を有効にできるようにする。
* **NVSHAS-9246**:CSV/PDFエクスポートのフィルタリングが機能しません。
* **NVSHAS-8947**：Rancher SSOで認証された場合、NV設定をインポートできない。
* **NVSHAS-9282**：UI：トークンが見つからないため、OpenShift レジストリエントリの編集に失敗しました。
* **NVSHAS-9098**：リスクページ読み込みのユーザーエクスペリエンスを向上させる。
* **NVSHAS-9267**：REST APIの変更のため、5.4マスタークラスタ上のUIを5.4以前のマネージドクラスタに切り替えられないようにしました。
* **NVSHAS-9285**：UI：ドロップダウンリストボタンが他の要素と重なる。
* **NVSHAS-9302**：FedReader および FedAdmin ロールを持つ APIKEY を作成できません。
* **NVSHAS-8539**：プロキシ設定を再設定するとパスワードが失われます。
* **NVSHAS-9293**:脆弱性レポートにおける無関係な画像の詳細の削除。
* **NVSHAS-9238**：クラスタ名が変更された後、UIが表示されたクラスタ名を更新しない。
* **NVSHAS-9363**：通知設定 > Webhooksグリッドが正しく配置されていません。
* **NVSHAS-9362**：セキュリティリスク脆弱性フィルターの検索結果は0件です。
* **NVSHAS-8699**：Rancher AD ユーザーが同じ場合、ユーザーを区別できません。
* **NVSHAS-9062**：同じユーザー名を持つRancher SSOユーザーをNV UIに表示する（コントローラー上の変換）。
* **NVSHAS-9071**：一部のモジュールは、コンテナスキャンのみでは報告されない。
* **NVSHAS-8242**: コントローラがクリティカルな重大度を扱うかどうかをテストするための gRPC 呼び出し。
* **NVSHAS-8908**：X-Forwarded-Portをカンマ区切りで正しく解析する。
* **NVSHAS-9024**：アドミッションコントロール 危険な役割のパフォーマンス
* **NVSHAS-9091**：ol:9.1、photon:5.0、rhel:9.1、amzn:2023 のすべてのモジュールをレポ、レジストリ、スタンドアロンのスキャンで報告できません。
* **NVSHAS-8997**：パフォーマンスを向上させるため、ノードあたりのポリシースロット数を大幅に削減。
* **NVSHAS-9059**：K8sから削除した後でも、NVにCRDグループが見える。
* **NVSHAS-9107**：rest.handlerConfigLocalCluster.
* **NVSHAS-9108**：ポート18500は開いてはいけない。
* **NVSHAS-9119**：probe.(*FileNotificationCtr).AddContainer()でゴルーチン・クラッシュ。
* **NVSHAS-9125**：無効な設定のCRDエントリーは作成が許可されるべきではない。
* **NVSHAS-9124**：Docker: 多くの予期しないヘルスチェック・プロセス・インシデントが報告されています。
* **NVSHAS-9111**：NVは`--event-qps > 0` をチェックすべきだ。
* **NVSHAS-9130**：特定のコンテナが開始された後に、予期しないコンテナ.パッケージ.更新インシデントが見つかる。
* **NVSHAS-9080**：Fed Readerのユーザーが一部のREST APIにアクセスできない。
* **NVSHAS-9092**：名前空間化されたユーザーはグローバルアセットを見るべきではありません。
* **NVSHAS-9116**：接続が切断された場合、ワーカークラスターは離脱することができます。
* **NVSHAS-8980**:oc 4.15でノードのホストとトンネルインターフェイスの取得に成功。
* **NVSHAS-9188**：mgmt-brインタフェースをハーベスタ・ノードのホスト・インタフェースとして設定する。
* **NVSHAS-4858**：ポリシー展開のパフォーマンスを向上させ、CPUとメモリの使用量を削減するために、コントローラのコンテナグループを拡張しない。
* **NVSHAS-8700**：Rancher AD ユーザーが{product-name} にログインできないことがある。
* **NVSHAS-9121**：グループのネットワーク監視しきい値の設定は編集できません。
* **NVSHAS-9189**：コントローラをシャットダウンして再起動すると、スキャンがスケジューリングでスタックする。
* **NVSHAS-9019**：ホスト・インターフェイスのリンク状態が同期していなかったのを修正。
* **NVSHAS-8305**：内蔵証明書を削除する。
* **NVSHAS-9013**：プロセスモニタのBPFフィルタの除去。
* **NVSHAS-7853**：TLSハンドシェイクEOF。
* **NVSHAS-9290**：ZDを有効にしても、ユーザーが追加したプロセス・プロファイル・ルールが有効にならない。
* **NVSHAS-9301**：ランチャープライムで展開されたNVは、ランチャーの味だとわからない。
* **NVSHAS-9289**：RBACがない場合にアップグレードを許可する。
* **NVSHAS-7601**：シナリオ中のPVコンフィグバックアップからのリストアを改善。
* **NVSHAS-7687**：エンフォーサーの syslog レベル設定を追加。
* **NVSHAS-9292**：Ingress Egressの脆弱性を修正。
* **NVSHAS-9270**:CISベンチマークパイプラインのk3sをサポート。
* **NVSHAS-9338**：管理クラスタ[id]がプライマリから切断されました。
* **NVSHAS-9358**：プロキシを使用した画像スキャンに失敗する。
* **NVSHAS-9337**：SYNフラッドが検出されたときにログメッセージを送信する。
* **NVSHAS-9209**：k8sから名前空間が削除されたときにドメインキャッシュを削除する。
* **NVSHAS-8985**：コントローラの再起動後、統合されたレジストリが消えます。

==== 既知の問題

* **NVSHAS-9443**：leases.coordination.k8s.ioオブジェクトを作成できないため、ArgoCDによるアップグレード/インストールに失敗しました。
* **回避策**ARGO CD を使用して 5.4.0 にアップグレードする前に、所定のリースオブジェクトを作成してください。名前空間がneuvectorと異なる場合は変更する。
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 2024年7月

==== バグ修正

* `host` と`tunnel` インターフェースは OpenShift CLI v4.15 で正常に取得されました。
* IPレンジ169.254.x.xはホストインターフェースIPから除外される。
* エンフォース起動後1分後にホストインターフェイスを再調査する。
* OpenID発行元URLの正規表現に失敗していた問題を修正しました。
* 以下の CVE を修正：
+
|===
| CVE | 適用対象 | インパクト

| CVE-2023-42364
| ビジーボックス
| {CVE-medium}

| CVE-2023-42365
| ビジーボックス
| {CVE-medium}

| CVE-2024-6197
| カール
| {CVE-medium}

| CVE-2024-6874
| カール
| {CVE-medium}

| CVE-2024-5535
| オープンスル
| {CVE-critical}

| CVE-2024-4741
| オープンスル
| {CVE-medium}
|===

=== 5.2.4-s5 2024年7月

* 以下の CVE を修正：

|===
| CVE | 適用対象 | インパクト

| CVE-2023-42363
| ビジーボックス
| {CVE-medium}

| CVE-2023-42364
| ビジーボックス
| {CVE-medium}

| CVE-2023-42365
| ビジーボックス
| {CVE-medium}

| CVE-2023-42366
| ビジーボックス
| {CVE-medium}

| CVE-2024-6197
| カール
| {CVE-medium}

| CVE-2024-6874
| カール
| {CVE-medium}

| CVE-2024-5535
| オープンスル
| {CVE-critical}

| CVE-2024-4603
| オープンスル
| {CVE-medium}

| CVE-2024-4741
| オープンスル
| {CVE-medium}
|===

=== 5.3.3 2024年6月

==== 機能強化

* `Admission Controls` ページから、ユーザーが特定のストレージクラスの使用をブロックできるようにする。
* `LDAP Authentication` には、`baseDN` と`groupDN` の設定用フィールドがある。
* `Egress and Ingress chart` 、各サービスの`High` 、`Medium` 脆弱性カウントを含む新しい脆弱性カラムがある。

==== バグ修正

* 複数エントリーの`Admission Control user criteria` でカンマ (`,`) を使用した場合の`regex` に関するバグを修正。
* `jar` パッケージの CVE スキャンで、同じ CVE の影響を受けるパッケージがすべて表示されないバグを修正しました。現在はすべての発生が報告されている。
* 以下の CVE を修正：

|===
| CVE | 適用対象 | インパクト

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== その他

* Helmチャートで{product-name} 、ユーザーが`updater-cron-job` のリソースを設定できるようにした。
* プロメテウス・エクスポーター・コンテナのバージョニングが見直され、`controller` のバージョニングとの関連が解消された。
* (スキャナ) Ubuntu と Red Hat Enterprise Linux の`R` パッケージ/モジュールを検出します。
* (スキャナ）PHP Composerのスキャンをサポート。

=== 5.2.4-s3 2024年4月

* 以下の CVE を修正：

|===
| CVE | 適用対象 | インパクト

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| エキスパット
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| ケアーズ
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| オープンスル
| {CVE-low}
|===

=== 5.3.2 2024年4月

==== バグ修正

* 以前のリリース（{product-name} ）からv5.3.1にアップグレードすると、既存のNvClusterSecurityRuleカスタムリソースが誤って削除されることがあります。注：アップグレードの問題を防ぐため、5.3.1 バージョンは docker hub から削除されました。

=== 5.3.1 2024年4月

[IMPORTANT]
====
5.3.2で修正されたアップグレードの問題を防ぐため、5.3.1バージョンはdocker hubから削除されました。5.3.2リリースをご利用ください。
====

==== 機能強化

* Githubのアクションを使用する際、ワークフローに影響を与えないよう、ユーザーが'`accepted`' 脆弱性を定義できるようにする。
* 深刻度、スコアレベル、およびフィード評価のフィルタを資産 > レジストリ > 画像の脆弱性ビューに追加しました。
* レジストリの設定時に、レジストリ画像のスキャンに定義されたプロキシを使用するかどうかを許可する。

==== バグ修正

* セキュリティリスク > 脆弱性 > アドバンスフィルタが「修正なしのCVE」をフィルタリングしない
* コンテナからホストモードコンテナへの予期せぬ違反
* docker api 1.24への切り替え時にOCIイメージフォーマットを受け入れる
* レジストリ スキャンで、画像以外のアーティファクトをスキャンしない / エラーを記録しない
* インターネットやシグストアに依存しないルートレス鍵ペア画像署名検証を可能にする。
* 特定のノードのネットワークルールで、セキュリティイベントが許可されない（「コンテナタスクが一杯です」というエラーメッセージに関連）。
* コンテナがワークロードに正常に追加できない（頻発）。チャネルメッセージによるデッドロックが原因。

==== その他

* Jenkins、GitHubアクション、Bamboo用のスキャナー・プラグインを更新。
* (Scanner) docker api 1.24 に切り替えたときに OCI イメージフォーマットを受け入れるように。
* (スキャナ)レジストリスキャンで、イメージ以外のアーティファクトをスキャンしないようにしました。
* (スキャナ) phpのコンポーザースキャンのサポートを追加。

==== {product-name} UIエクステンションランチャー用1.0 2024年3月

* {product-name} のインストール後、Rancher から{product-name} UI Extension をxref:rancher.adoc#_suse_security_ui_extension_for_rancher[有効化/インストール]すると、{product-name} クラスタ全体への SSO へのリンクを含むクラスタのダッシュボードが表示されます。注：拡張機能がサードパーティと表示されることがありますが、将来のリリースで修正される予定です。また、インストール後、Rancher 2.7.xユーザは、リストに2つの{product-name} UI Extアイコンが表示されることがあります（バグ）。一方のアイコンには「アンインストール」（インストール済みという意味）と表示され、もう一方には「インストール」と表示されるはずだ。つまり、拡張機能がすでにインストールされている場合は、再度インストールしない。

=== 5.2.4-s2 2024年2月

* 以下の CVE を修正：
* cveが高い：expat の CVE-2023-52425、openjdk11 の CVE-2024-20952 および CVE-2024-20918
* Med cve：expat の CVE-2023-52426、openjdk11 の CVE-2024-20926、CVE-2024-20921、CVE-2024-20945 および CVE-2024-20919、openssl の CVE-2024-0727 および CVE-2023-6237

=== 5.3.0 2024年2月

==== 機能強化

* ダッシュボード（egress）、PDF、CSVレポート、およびネットワーク・アクティビティ画面とセキュリティ・イベント（違反）リストに外部宛先URL（FQDN）を表示します。
* Discoverモードでは、外部FQDNアドレスグループへのイグレスを自動的に学習する。外部接続が既存のルールに一致しない限り、新しい外部FQDNカスタムグループが作成される。
* 新しいController環境変数CTRL_EN_ICMP_POLICY = 1により、ICMPの学習（Discoverモード）とブロック（Protectモード）を有効にする。
* CRDをGithubにエクスポートし、コンソールまたはREST APIを使用してデフォルトのリポジトリへのgitopsをサポートします。
* ADFS iDPでSAML SSOシングル・ログアウトをサポート
* ARM64プラットフォームのサポートを追加。ARMベースのプラットフォームからプルすると、自動的に適切なARM64{product-name} イメージがプルされます。
* プロキシ経由のウェブフックをサポート
* アドミッション・コントロールの監査機能を改善し、すべてのルールの結果を含める。すべてのルールの結果をリストアップし、アドミッション・コントロールの実運用で評価されたときに発生する最終的なアクションのための別のエントリを追加する。
* 無効化されたアドミッション・コントロール・ルールをCRDまたはyaml (kubectl)経由で適用する。
* コンソール、CRD、または REST API を介した脆弱性プロファイルのエクスポート/インポート。インポートは既存のプロファイルを置き換えます。CRDを削除すると、プロファイルは空になります。
* コンソール、CRD、または REST API を使用したコンプライアンス・プロファイル・テンプレートのエクスポート/インポート。インポートは既存のテンプレートを置き換えます。
* ユーザーが手動で実行する必要がある（{product-name} では実行されない）CIS ベンチマークのコンプライアンス・レポートに「手動」ステータスを追加する。
* 脆弱性ページのUI読み込み/パフォーマンスの改善
* ブラウザのセッションログインを統一する。これにより、ブラウザ内のすべてのタブが同じログイン・セッションを共有し、既存のセッションから新しいタブを開いても認証情報は要求されず、1つのタブがログアウトするとすべてのタブがログアウトする。
* コンソール（UI）のセキュリティ強化：1) 必須のセキュリティ・ヘッダを追加する（X-Content-Type-Options nosniff; X-XSS-Protection 1; mode=block; X-Frame-Options SAMEORIGIN; Cache-Control private, no-cache, no-store, must-revalidate HTTP Strict Transport Security max-age=15724800, 2) CSPヘッダを追加する（例えば、'`default-src`' ディレクティブを設定する）, 3) サーバ名の開示を削除する。
* CISベンチマークの新しいバージョンをサポートする。Kubernetes（1.8.0）、Kubernetes V1.24（1.0.0）、Kubernetes V1.23（1.0.1）、RedHat OpenShift Container Platform（1.4.0）
* 資産に表示-> コンテナ-> コンテナの詳細 レジストリとランタイムでスキャンされたコンテナ
* セキュリティリスク-> 脆弱性-> 影響ポップアップにグループへのリンクを追加し、グループモードを簡単に編集できるようにした。
* 画像やコンテナの脆弱性ページへのURLのディープリンクをサポートする。
* 管理者がコンソールでユーザーパスワードをリセットするためのパスワードリセットオプションを追加 設定-> ユーザー
* Settings-> Configuration-> Notificationで、イベントログをコントローラのポッドログに送信できるようにします。送信されるイベントは'notification='で始まり、リーダーコントローラポッドにのみ保存される。このバージョンには、イベントレベルを変更するためにSYSLOGを有効にしなければならないというバグがあることに注意してください（レベルを変更した後、必要に応じて無効にすることができます）。
* コントローラ/エンフォースメントが"/host/cgroup "をマウントするための要件を削除。
* スラック、ドキュメント、その他のリソースへのリンクを含む「サポートを受ける」メニューの追加
* メッセージ・フィールドを/v1/log/アクティビティ・ログに埋める

==== バグ修正

* セキュリティリスクにおける内部サーバーエラー-> CVE数の多い脆弱性
* SIGSEGV: コントローラーのセグメンテーション違反
* 脆弱性のあるファイル（jarなど）を削除しても脆弱性リストから削除されない
* 署名アルゴリズム SHA256withECDSA を使用した無効な Syslog 証明書
* {product-name} ネットワークルールで許可されるべきセキュリティイベントを示す。
* ゾンビ」エンフォースメントが動作している非管理ノード
* 高度なフィルタでは、修復と影響フィールドが空白になる
* エンフォーサーの予期せぬ再起動を防ぐため、文字列の処理を修正した。
* ビルトイン・グループに関する予期せぬ違反
* サポートバンドル・エンフォーサーのデバッグRPCコールがエラーを返す
* セキュリティ・イベントでグループが一致しない
* slackへのイベント送信がうまくいかない - プロキシ使用時
* 許可されたネットワークルールのセキュリティイベントを表示する

==== その他

* Helmチャートにランタイムコンテナエンジン（ソケット）の自動検出機能を追加
* Helmチャートの特権モードでコントローラを実行する設定と、コントローラ/エンフォーサが"/host/cgroup "をマウントする要件を削除しました。
* {product-name} ドキュメントから kubernetes デプロイメントファイルのサンプルが削除されました。例についてはリンクを参照されたい。

==== 手動デプロイで変更が必要になる可能性のある変更点のハイライト（すべての変更は5.3.xの最新のHelmチャートに反映済みです。）

* コンテナランタイム（ソケット）の自動検出により、コンテナランタイムとソケットパスを指定する必要がなくなる。
* 特権モードでコントローラを実行する必要がなくなったため、ランタイムソケットをマウントする必要がなくなり、/host/cgroup/がマウントされました。
* yamlにneuvector-secretだけでなく、neuvector-binding-secretのrole/roleバインディングを追加。
* 5.3で必要となる新しいサービスアカウントとロールバインディング
* 参照されるすべてのデプロイメントyamlファイルのパスに/5.3.0/が追加されました。

=== 5.2.4-s1 2024年1月

==== セキュリティパッチリリース

* openssl の CVE-2023-6129 および curl の CVE-2023-46219, CVE-2023-46218 を修正。

=== 5.2.4 2023年11月

==== バグ修正

* Azure AKS ValidatingWebhookConfigurationの変更とエラーログ。

=== 5.2.3 2023年11月

==== 機能強化

* スキャナーにNVD API 2.0のサポートを追加。
* スキャナ単体モードでコンテナホストをスキャンする。

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== バグ修正

* docker cp / grpcのデッドロック問題により、ノード上のスキャンに失敗しました。

=== 5.2.2-s1 2023年10月

==== セキュリティ・アップデート

* High CVE-2023-38545 および CVE-2023-43804 を含む CVE を修正するためにパッケージを更新してください。

=== 5.2.2 2023年10月

==== CVE-2023-32188 に関するセキュリティ勧告

* デプロイ時とアップグレード時に JWT トークンの署名に使用する証明書を自動生成し、Helm ベースのデプロイ時に Manager/RESTful API 証明書を自動生成することで、CVE-2023-32188"`JWT token compromise can allow malicious actions including Remote Code Execution (RCE)`" を修正しました。
 ** JWT署名用の証明書は、コントローラによって自動的に作成され、有効期間は90日で、自動的にローテーションされる。
 ** Manager、REST API、およびレジストアダプタ証明書の自動生成には、{product-name} helm バージョン 2.6.3 以降を使用した Helm ベースのインストールが必要です。
 ** 組み込みの証明書は、デプロイ時に置き換えない場合、yamlベースのデプロイメントでも使用されますが、置き換えることを推奨します（次の行を参照）。
 ** 手動によるxref:replacecert.adoc[証明書の置き換えは]まだサポートされており、以前のリリースやyamlベースのデプロイメントで推奨されています。説明については、{product-name} GitHubセキュリティ勧告https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[こちらを]参照のこと。
 ** ユーザー提供の証明書の使用は、Helmとyamlベースのデプロイメントの両方で、これまで通りサポートされています。
* カスタムコンプライアンススクリプトの制御を追加します。デフォルトでは、ControllerとEnforcerに環境変数CUSTOM_CHECK_CONTROLが追加されない限り、カスタムスクリプトは追加できないようになりました。値は、"disable"（デフォルト、許可されない）、"strict"（管理者の役割のみ）、または "loose"（管理者、コンプライアンス、ランタイムポリシーの役割）である。
* LDAPインジェクションの防止 - ユーザー名フィールドをエスケープ。

==== 機能強化

* SYSLOGから送信されるCVE結果に、レイヤードスキャン用の追加スキャンデータを追加する。
* CVEデータベースのスキャンにNVD API 2.0をサポート
* Assets-> Container details でコンテナ・イメージのビルド日を提供する。
* ネットワーク ルールの並べ替えを調整： ネットワーク ルール ビューでは並べ替えを無効にし、グループ ビューでは並べ替えを有効にします。
* Enforcer THRT_SSL_TLS_1DOT0、THRT_SSL_TLS_1DOT1に環境変数を設定して、TLS 1.0およびTLS 1.1の検出/アラートを有効/無効にします。デフォルトでは無効。
* コントローラおよびエンフォーサーに環境変数AUTO_PROFILE_COLLECTを追加し、メモリプレッシャーイベントの調査時にメモリ使用量をキャプチャできるようにしました。値を 1 に設定すると有効になる。
* アドミッション・コントロールに対する構成評価は、1回のスキャンですべての違反を示すべきである。
* 応答ルールの CVE レポート基準のオプションを追加しました。例1-"cve-high-with-fix:X "の意味：(修正された高い脆弱性)の数がXを超えたら、対応ルールを発動する。例2-"cve-high-with-fix:X/Y "の意味：(Y日前に報告され、修正された高い脆弱性) >= Xのとき、対応ルールをトリガーする。

==== バグ修正

* グループポリシーのエクスポートが実際のYAMLコンテンツを返さない
* 専用機能による名前空間のプルーニングの改善
* {product-name} namespaceユーザーはアセットを見ることができない-->namespaces
* CRのネームスペースが既に削除されている場合、CRDのCREATE/UPDATEリクエストの処理をスキップする。
* ネームスペースの削除後にCRDグループの一部が正常にプルーニングされない場合の回避策を提供する。

=== 5.2.1 2023年8月

==== 機能強化

* SYSLOGメッセージでレイヤスキャン結果と追加のCVEデータを報告する。これは、Settings-> Configuration-> SYSLOG のチェックボックスで有効になります。
* エクスポートされたcsvコンプライアンスレポートのNIST 800-53マッピング（docker CISベンチマークへの）。
* 画像署名検証のプロキシ設定をサポート
* ダウンロードしたCVEレポートに画像署名スキャン結果を含める
* カスタム基準を通じて利用可能な、アドミッション・コントロール・ポリシーのポッド注釈のサポート
* 脆弱性レポート印刷のフィルタに Last Modified フィールドを追加。

==== バグ修正

* AWS 課金（CSP アダプタ）の初期デプロイメント（{product-name} ）において、デフォルトの admin とデフォルトのパスワードを作成しない。
* .jsonファイルのサイズが大きくなり、kubernetesノードをクラッシュさせていたのを修正した。
* SQLインジェクション検出ロジックの改善
* {product-name} 、コア・チャートをインストールする前にヘルムCrdチャートをインストールすると、サービス・アカウントが見つからない。
* イメージスキャンI.4.1のコンプライアンス結果が正しくない
* 他のすべてのネームスペースからの画像を表示する脆弱性高度フィルタレポート

=== 5.2.0 2023年7月

==== 機能強化

* {product-name} API アクセス用のトークンをサポートする。新しいAPIキーを作成するには、設定-> ユーザ、APIキー... を参照してください。キーはデフォルトまたはカスタムのロールに設定できます。
* {product-name} 月額サポートサブスクリプションのAWS Marketplace PAYG課金をサポート。ユーザーは、前月の平均ノード数使用量に基づいてAWSアカウントに毎月課金される、SUSEサポートによる{product-name} 。詳細は https://open-docs.neuvector.com/deploying/awsmarketplace[こちら]
* 入場制限のための画像署名をサポートする。ユーザーは、Sigstore/Cosignとの統合により、イメージを本番環境にデプロイする前に、{product-name} 、特定の当事者によって署名されていることを検証するよう要求することができる。新しい署名アセットの作成については、アセット-> Sigstore Verifiersを参照。ルールは、基準画像署名および/または画像シグストア・ベリファイアで作成できます。
* 各アドミッション・コントロール・ルールが、MonitorまたはProtectの各モードを持つようにする。MonitorモードでのDenyアクションは警告を発し、ProtectモードでのDenyアクションはブロックする。アクションを許可しても影響はない。
* Policy > Admission Control > Add Rule for Users and User Groups]で、正規表現をサポートする新しい正規表現演算子を追加します。ANY regex in "と "NONE regex in "演算子をサポート。
* リソース制限などのアドミッション・コントロール基準のサポートを追加する。リソース制限に新たな基準が追加され、カスタム基準設定によって追加基準がサポートされる。
* https://github.com/goharbor/pluggable-scanner-spec[プラガブル・スキャナー・インターフェイスを通じて]、ハーバーのレジストリから{product-name} スキャナーを呼び出すことをサポート。そのためには、コントローラへの接続を設定する必要がある(公開API)。Harborアダプタは、コントローラのエンドポイントを呼び出してスキャンをトリガする。尋問サービスは定期的なスキャンに使用できる。フェデレーションプライマリコントローラからのスキャン結果は、リモートクラスタに伝搬されます。 注：HTTPSベースのアダプタのエンドポイントエラーに問題があります：Test Connectionエラーは無視してください。
* CVEを検索できるSaaSサービス。最新の{product-name} CVEデータベースを検索し、特定のCVEがデータベースに存在するかどうかを確認する。このサービスは、{product-name} プライム（有料サポート加入）のお客様にご利用いただけます。SCCポータルからサポートにアクセスしてください。
* WAF/DLPの機能は維持したまま、ネットワーク保護を無効にできるようにする。Settings-> ConfigurationでNetwork Policy Enablementを設定する。
* {product-name} 、各コンポーネントに必要な、より特権の低いサービスアカウントを使用する。変数"`leastPrivilege`" 。デフォルトはfalseである。注：5.2.0より前のリリースでこの変数を使用して現在のヘルムチャートを使用すると、正しく機能しません。
* CIS 1.5 5.1.5勧告を満たすために、デフォルト以外のサービスアカウントにバインドする。
* 管理者は、設定-> ユーザー、APIキー、およびロールで、ユーザーのデフォルトのセッションタイムアウトを設定できます。
* カスタマイズ可能なログインバナーとカスタマイズ可能なUIヘッダーテキスト。コンフィギュレーションに必要な条件はxref:customui.adoc[こちらを]ご覧ください。
* TLS暗号化トランスポートのSYSLOGサポート。Settings-> Configuration for SYSLOGでTCP/TLSを選択する。
* Rancher Managerから{product-name} モニターヘルムチャートのデプロイを有効にします。
* レジストリスキャン用のURLバリデータで、トップレベルドメインの上限を削除しました。
* ランタイムスキャンを含む、golangの依存関係をスキャンする。
* Debian 12 (Bookworm) の脆弱性スキャンをサポート。
* レジストリ/詳細のCSVエクスポートを追加し、設定されたレジストリ内のすべてのイメージのCVEを、選択されたレジストリのアセット-> レジストリにエクスポートできるようになりました。
* {product-name} 、x.509証明書フィールドに複数のADFS証明書を並行して設定できるようにする。
* レスポンス・ルールのコメント・フィールドを追加して表示します。
* {product-name} がシステム・コンテナとみなすものを、環境変数で指定する。例えば、Rancherとデフォルトの名前空間について：NV_SYSTEM_GROUPS=*cattle-system;default
* Kubernetes 1.27とOpenShift 4.12のサポート追加

==== バグ修正

* エンフォーサー/コントローラーのログの繰り返しを減らす。
* 複数のクラスタのページがレンダリングされない。
* 空のグループの自動削除に2時間かかる。
* 手動で許可したネットワークルールが適用されず、一時停止画像が違反となる。
* 特定の初期条件下でネットワークルールがトラフィックを許可していても、SSL接続をブロックする。
* 同期のポリシー更新の問題により、許可されたネットワークルールでもセキュリティイベントの警告が表示される。
* ネットワーク・アクティビティが、カスタム・グループのトラフィックを誤って外部に関連付ける。
* 各ポッドにマウントされているネームスペースのデフォルトのサービス・アカウント・トークンが高すぎる特権です。
* ネットワークルールを定義したにもかかわらず、コンテナがメモリ不足（OOM）エラーで停止した場合に、セキュリティイベントに違反が記録される（誤検出）。
* クラスタ内の管理されていないコンテナの検出と保護を無効化/有効化できるようにする。これは Manager CLI で設定できる：

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== その他

* Helmチャートに "leastPrivilege "設定を追加。New_Service_Profile_Baselineにhelmオプションを追加しました。新しいHelmチャート（コア）のバージョンが5.2用に公開されました。
* HelmチャートでAWS Marketplace（課金アダプタ）の統合設定を有効にする。
* 新機能(複数のADFS証明書、ゼロドリフト、New_Service_Profile_Baseline、SYSLOG TLS、ユーザータイムアウト)をサポートするためにconfigmapを更新する。
* サポートされるKubernetesのバージョンを1.19+、OpenShift 4.6+に更新（CRI-Oでは1.19+）。

=== 5.1.3 2023年5月

==== 機能強化

* Microsoft .NETフレームワークをスキャンするための新しい脆弱性フィードを追加。
* プロメテウス・エクスポーターでは、スケーラビリティを向上させるため、エンフォーサー統計がデフォルトで無効になっている。
* ユーザビリティの向上：スキャナーを使って1枚の画像をスキャンし、その結果を印刷する（下の例を参照）。
* アドミッション・コントロール・ルールの基準にimagePullPolicyチェックを追加。
* CRDスキーマが古い場合に警告メッセージを表示する。

==== バグ修正

* ネットワークアクティビティ画面が表示されない、または正しく表示されない。
* 空のグループの自動削除に2時間かかる。
* コンプライアンス・プロファイルがUIコンソールに表示されない。
* セキュリティイベントの高度なフィルタに「エラー」レベルがない。
* 保存したパスワードに特殊文字が含まれていると、次回以降の認証に失敗します。
* リクエスト数が多い場合、マルチクラスターページが正しくレンダリングされない。
* レジストリの詳細（下部）ペインが更新されない。

==== スキャナーサンプル出力

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 2023年3月

==== 機能強化

* バーチャルホストベースのアドレスグループとポリシーマッチングによるネットワーク保護をサポート。これは、2つの異なるFQDNアドレスが同じIPアドレスに解決されるが、それぞれのFQDNに対して異なるルールが適用されるべきであるというユースケースを可能にする。この保護を有効にするには、'`vh:`' インジケーターを使用して、'`address=vh:xxx.yyy`' を持つ新しいカスタムグループを作成することができます。ネットワークルールは、（解決されたIPアドレスの代わりに）仮想ホスト名に基づいて、'`From`' ソースとしてカスタムグループを使用し、仮想ホストに対して異なるルールを適用することができます。
* 終了したコンテナを除外するためのコンプライアンス・コンテナ・リスト。
* DLPルールを強化し、パターン内の単純なワイルドカードをサポートする。
* cri-o 1.26+とOpenShift 4.11+のサポートを追加。
* グラビアをオプションにする。
* コンソール / UI にクラスタ名前空間リソースを表示します。
* ソースの深刻度/分類（例：Red Hat、Ubuntu... ）と NVD の深刻度スコアをコンソールに表示します。
* ユーザーがSSOで認証されている場合、RancherとOpenShiftでSSO/RBACの無効化を許可しない。
* 自動スキャンの有効化と未使用グループの削除をconfigMapに追加。
* 暗黙の拒否違反のため、csv/pdfに外部ソース/宛先のIPアドレスを含める。
* コントローラとエンフォースメントのCPUとメモリ使用量に関する様々なパフォーマンスとスケーラビリティの最適化。

==== バグ修正

* GKE Container Optimized OS (COS)ノードのプロテクトモード時のアプリケーションの遅さを修正しました。
* SUSE Linux (SLES) 15.4 CVE がスキャナでマッチしない。この修正により、深刻度がフィードで提供された場合、NVDレコードが欠落していても、その脆弱性はデータベースに追加される。レポートにはCVEスコアのない脆弱性が含まれている可能性がある。

==== その他

* ヘルムでのアドミッション・コントロールCRDオプションの強化 https://github.com/neuvector/neuvector-helm/pull/237.
* 新しいエンフォーサー環境変数をヘルムチャートに追加。

=== 5.1.1 2023年2月

==== 機能強化

* 検出された脆弱性の syslog-event に情報として"`package`" を追加する。
* Enforcer 環境変数 ENF_NETPOLICY_PULL_INTERVAL を追加する - ポリシーの更新/再計算による Enforcer のネットワークトラフィックとリソースの消費を削減するための秒単位の値 (推奨値 60)。(注：2023年8月までは文書化されていない追加事項だった）。

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== バグ修正

* 空のグループ削除エラー "オブジェクトが見つかりません"
* 同じコンテナ内のトラフィックの警告/ブロック
* 許可ルールが設定されたistioのegressトラフィックに対する予期せぬ暗黙の違反
* {product-name} 4.x リリースからのアップグレード時に、不正なポッドグループメンバーシップが予期しないポリシー違反を引き起こす。
* リクエストに余分なエンコード文字が含まれる場合、ADFSでOIDC認証に失敗する
* dpによるポッドの作成と削除でメモリ使用量が多い
* Manager を含むいくつかの CVE を修正するため、alpine を更新：CVE-2022-37454、CVE-2022-42919、CVE-2022-45061、CVE-2021-46848、Enforcer：CVE-2022-43551、CVE-2022-43552
* 様々なUIのバグを修正

==== その他

* ヘルムチャートが更新され、社内通信用証明書の交換が可能に

=== 5.1.0 2022年12月

==== 機能強化

* 集中型マルチクラスタースキャン（CVE）データベース。プライマリ（マスタ）クラスタは、連携レジストリとして指定されたレジストリ/レポをスキャンできます。これらのレジストリからのスキャン結果は、すべての管理対象（リモート）クラスタに同期される。これにより、管理クラスタコンソールでのスキャン結果の表示と、管理クラスタのアドミッション制御ルールでの結果の使用が可能になります。レジストリのスキャンはクラスタごとに行うのではなく、1回で済むため、CPU/メモリとネットワーク帯域幅の使用量を削減できる。
* アドミッション・コントロール・ルールを強化する：
 ** アドミッション・コントロール・ルールのカスタム基準。例えば、item.metadata.annotationsKeyに'neuvector'が含まれる、item.metadata.name='xyzzy'が含まれるなどです。
 ** Podのデプロイ時に、サービスアカウントに対してリスクの高いRBAC設定をチェックする基準を追加しました。これらの基準には、「ワークロード・リソースのあらゆる操作」、「RBAC上のあらゆる操作」、「ワークロード・リソースの作成」、「秘密の一覧表示」、「コンテナへの実行」が含まれる。
 ** アドミッション・コントロール・ルールのモジュールにセマンティック・バージョン比較を追加。これにより、ルールのバージョン番号に > または < 演算子を適用できるようになります（例：curl<6.2.0 のモジュールのデプロイを許可しない）。これにより、インストールされたパッケージの特定のバージョンをチェックすることができる。
 ** Kubernetes 1.25+でサポートされるPod Security Admission (PSA) のアドミッション制御ルールを追加。
* 新しい環境変数NO_DEFAULT_ADMINを追加し、これを有効にすると'admin'ユーザーを作成しない。これはデフォルトでRancher SSO統合に使用されます。有効になっていない場合、デフォルトの管理者パスワードがデフォルトから変更されていない場合、変更するようにユーザーに警告し、イベントを記録する。
* ログインに失敗した後、ログインをブロックすることがデフォルトになりました。デフォルト値は試行回数5回で、設定-> ユーザーと役割-> パスワードプロファイルで設定可能です。
* パフォーマンスチューニングのための新しい環境変数ENF_NO_SYSTEM_PROFILESを追加："1".有効にすると、プロセスモニターとファイルモニターが無効になる。学習プロセス、プロファイルモード、プロセス/ファイル（パッケージ）インシデント、ファイルアクティビティモニタは実行されない。これにより、CPU/メモリリソースの使用量とファイル操作が削減される。
* スキャナポッドのカスタム自動スケーリング設定を追加しました。重要だ：スキャナーが OpenShift オペレーターでデプロイされている場合、オペレーターは常にポッド数を設定値に変更するため、スキャナーの自動スケーリングはサポートされません。
 ** *_遅延戦略：_*
  *** リードコントローラが「タスクカウント」＞0を90秒以上継続的に確認した場合、maxScannerPodsに達していなければ、新しいスキャナポッドが開始される。
  *** リードコントローラが "タスクカウント "が0であることを180秒以上継続的に確認した場合、minScannerPodsに達していなければ、スキャナポッドを1つスケールダウンする。
 ** *_当面の戦略_*
  *** リードコントローラが "タスクカウント">0を検出するたびに、maxScannerPodsに達していなければ、新しいスキャナポッドが起動される。
  *** リードコントローラが "タスクカウント "が0であることを180秒以上継続的に確認した場合、minScannerPodsに達していなければ、スキャナポッドを1つスケールダウンする。
* カスタムグループは、Rancherの名前空間ラベルを含む名前空間ラベルを使用できるようになりました。一般的に、ポッドとネームスペースのラベルをカスタムグループに追加できるようになりました。
* ネットワーク・アクティビティ・ビューで、選択したネームスペースやグループを非表示にする機能を追加。
* Cilium cniをフルサポート。
* OpenShift 4.9および4.10をフルサポート。
* {product-name}/オープン・ゼロ・トラスト（OZT）プロジェクト用のビルド・ツールが、以下のサイトで公開されている。 https://github.com/openzerotrust/openzerotrust.io.
* {product-name} に、コントローラ、マネージャ、エンフォーサの各バージョンのバージョンIDとSHA256ダイジェストが表示されるようになりました。 https://github.com/neuvector/manifests/tree/main/versions.
* 匿名テレメトリーデータ（ノード数、グループ数、ルール数）は、プロジェクトチームが使用状況を理解するのに役立つように、デプロイ時にRancherクラウドサービスに報告されるようになった。これはUI、configMap (No_Telemetry_Report)、またはREST APIで無効化（オプトアウト）できます。
* (2023年1月補遺）。IstioでServiceEntryベースのネットワークポリシーをサポート。バージョン5.1.0では、Istioで宣言されたServiceEntry宛先へのポッドに対して、Egressネットワークポリシーの強制機能が追加されました。通常、ServiceEntryは、DNS名で参照される外部サービスが宛先IPにどのように解決されるかを定義する。v5.1以前では、{product-name} 、ServiceEntryへの接続を検出してルールを適用することができなかったため、すべての接続がExternalに分類されていた。5.1では、特定のServiceEntry宛先に対してルールを適用できる。重要：Istioベースのデプロイメントでv5.1にアップグレードする場合は、これらの接続を許可し、違反アラートを回避するための新しいルールを作成する必要があります。アップグレード後、許可ルールが存在しない場合、新たに可視化されたトラフィックに対して暗黙的違反が報告されます。ディスカバーモードでは、新しいトラフィックルールを学習し、自動作成することができる。このトラフィックを許可するには、グループを検出モードにするか、アドレス（またはDNS名）を持つカスタムグループを作成し、この宛先への新しいネットワークルールを作成してトラフィックを許可する。注：5.1.0では、deny違反によって報告される宛先が正しい宛先を表していないというバグがあります。 バグレポートでは、サーバー名とクライアント名の両方が同じになっています。 この問題は今後のパッチリリースで対処される予定だ。

==== バグ修正

* ローリングアップデート時に作成される不要なcisベンチマークデータによるコントローラのメモリ消費を削減。この問題は新しいデプロイメントでは発生しません。
* 設定画面からライセンスを削除します。

=== 5.0.6-s1 2023年3月

==== バグ修正

* CVE-2023-23914, CVE-2023-23915, CVE-2023-23916 を含む curl の CVE を修正するため alpine パッケージを更新

=== 5.0.6 2023年2月

==== バグ修正

* dpMsgConnectionのメモリ使用量が多い
* 管理されていないワークロードで学習されたポリシー・ルールが多い場合、エンフォーサのdpプロセスでメモリ使用量が多い（メモリ・リーク）
* コンテナ上のトラフィックをスニファリングする際、tcpdumpが正常に起動できない。
* Manager を含むいくつかの CVE を修正するため、alpine を更新：CVE-2022-37454、CVE-2022-42919、CVE-2022-45061、CVE-2021-46848、Enforcer：CVE-2022-43551、CVE-2022-43552

=== 5.0.5 2022年11月

==== バグ修正

* 5.0.xにアップグレードすると、Manager、Controller、Enforcerのバージョンが異なるというエラーメッセージが表示されます。
* エンフォーサーは日常的なパニックを経験し、その結果、Dpを殺害した。 WebUI にエンフォーサーがオンラインとして反映されない。
* coreosのNV.Protectグループで、予期しないProcess.Profile.Violationが発生しました。

=== 5.0.4 2022年10月

==== セキュリティ・アップデート

* alpine を更新し、manager の expat ライブラリに存在する致命的な CVE-2022-40674 とその他のマイナーな CVE を除去。

==== 機能強化

* アントレアCNIのサポートを追加

==== バグ修正

* NV.Protectグループにおける予期せぬprocess.profile.violation事件を修正。
* マネージャーUIアクセスでSSLが無効の場合、ユーザーパスワードがマネージャーログに出力される。

=== 5.0.3 2022年9月

==== 機能強化

* 永続ボリュームからの再起動に成功した後、EULAを表示しない。
* 脆弱性プロファイル設定の画像フィルタを使用して、コンテナのスキャン結果をスキップする。
* GitHubアクションのサポートスキャナー https://github.com/neuvector/neuvector-image-scan-action.
* 秘密スキャンを無効にし、CISベンチマークを実行するためのEnforcer環境変数を追加する。

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== バグ修正

* エンフォーサーが始動できないことがある。
* マルチクラスターフェデレーション環境におけるコネクションリーク。
* セキュリティリスク-> コンプライアンスにおいて、コンプライアンスページが読み込まれないことがある。

=== 5.0.2 2022年7月

==== 機能強化

* Rancherのハード化クラスタとSELinuxクラスタがサポートされている。

==== バグ修正

* k3sシステムでエージェントプロセスのCPU使用率が高い。
* 5.0へのアップグレード後、AD LDAPグループが正しく動作しない。
* Enforcerは、エラー=開いているファイルが多すぎる（rke2/cilium）ために再起動し続けます。
* サポートログが正常にダウンロードできません。

=== 5.0.1 2022年6月

==== 機能強化

* openSUSE Leap OS の脆弱性スキャンをサポート（スキャナイメージ）。
* スキャナー：イメージレポの再構築時にワイプアウト属性を実装。
* {product-name} の展開と SELinux が有効なホストのサポートを確認する。ヘルムチャートが更新されるまでの暫定的なパッチの詳細については、以下を参照のこと。
* Rancher UIでFeature ChartとPartner Chartをより目立つように区別する + Rancher helm chartでnginxのingressアノテーションを改善する。nginx.ingress.kubernetes.io/backend-protocol に ingress.kubernetes.io/protocol: https を追加/更新しました："HTTPS".
* 現在の OpenShift Operator は、API とフェデレーション・サービスのパススルー・ルートをサポートしています。エッジおよび再暗号化ルート終端タイプをサポートするために、追加のHelm値パラメータが追加されました。

==== バグ修正

* AKSクラスタがアドミッション・コントロールのウェブフックに予期しないキーを追加する可能性がある。
* k8s 1.24クラスタと1.64 containerdランタイムでEnforcerが動作しない。これとは別に、エンフォーサーが起動しないことがある。
* クラスタをフェッドマスターに昇格させる管理者ロールユーザー（ローカルユーザーまたはSSO）は、自動的にfedAdminロールに昇格する必要があります。
* sso がマスタークラスタ上の{product-name} に Rancher デフォルトの admin を使用している場合、{product-name} のログインロールは fedAdmin ではなく admin になります。
* いくつかのゴルーチンのクラッシュを修正。
* ノードに関連付けられていないホスト IP からの暗黙の違反。
* ComplianceProfileにPCIタグが表示されない。
* LDAPグループマッピングが表示されないことがある。
* リスクレビューと改善ツールは、「システム設定の更新に失敗しました：リクエストの形式が間違っています」。
* OKD 3.11 - Clusterroleエラーが存在しても表示される。

==== CVEの修復

* すべてのイメージの ncurses パッケージに高度の CVE-2022-29458 の cve が発見されました。
* アップデータイメージの curl パッケージに高度の CVE-2022-27778 および CVE-2022-27782 が見つかりました。

==== SELinuxサポートの詳細

{product-name} は、SELinuxが有効なクラスタをデプロイして機能させるための追加設定を必要としない。RHEL 8.5ベースのSELinux対応RKE2ハーデンクラスターで{product-name} 。PSPが有効で、パッチマネージャとスキャナのデプロイメントがあれば、{product-name} 。次のチャート・リリースでは、以下の問題が修正されるはずだ。

Rancherチャートからpspを有効にする例を添付し、ManagerとScannerのデプロイメントにパッチを適用するコマンドを以下に示します。patchコマンドのユーザーIDには任意の数字を指定できる。

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

PSPを有効にする例：

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 一般提供（GA）リリース 2022年5月

==== 機能強化

* グループ・モードの自動プロモーション。経過時間と基準に基づいてグループの保護モードをプロモートする。CRDが作成したグループには適用されない。この機能により、新しいアプリケーションを一定期間Discoverで実行し、動作を学習し、{product-name} 、NetworkとProcessの許可リストルールを作成し、その後自動的にMonitor、Protectモードに移行する。モニター基準への発見：グループ内の少なくとも1つのライブポッドのすべてのネットワークとプロセスのアクティビティを学習するための経過時間。保護するためのモニター当グループに設定された時間枠において、セキュリティイベント（ネットワーク、プロセスなど）は発生していない。
* Rancher 2.6.5のアプリとマーケットプレイスチャートをサポート。cattle-neuvector-systemネームスペースにデプロイし、Rancherから{product-name} へのSSOを可能にする。注：新しいチャートに更新するためには、Rancherからの以前のデプロイメント（例えば、パートナーカタログチャート、バージョン1.9.x以前）を完全に削除する必要があります。
* SUSE Linux (SLE, SLES) および Microsoft Mariner のスキャンをサポートします。
* ゼロドリフトのプロセスとファイル保護。これはプロセスとファイルの保護に関する新しいデフォルトモードである。ゼロ・ドリフトは、元のコンテナ・イメージの親プロセスに由来するプロセスのみを自動的に許可し、ファイルの更新や新規ファイルのインストールを許可しない。DiscoverまたはMonitorモードでは、zero-driftは不審なプロセスやファイルの活動に対して警告を発します。プロテクトモードでは、そのような活動をブロックする。ゼロドリフトでは、プロセスを学習したり、許可リストに追加したりする必要はない。グループのゼロドリフトを無効にすると、そのグループにリストされているプロセスとファイルのルールが代わりに有効になります。
* ネットワーク、プロセス、ファイルのための分割ポリシーモード保護。設定]-> [設定]で、ネットワークルールの実施に必要なネットワーク保護モードを個別に設定できるグローバル設定が追加されました。これを有効にすると (デフォルトは無効)、すべてのネットワーク ルールが選択された保護モード (検出、監視、保護) になり、プロセス/ファイル ルールはそのグループの保護モードのままになります (Policy-> Groups 画面に表示されます)。このようにして、ネットワークルールはプロテクト（ブロック）に設定し、プロセス/ファイルポリシーはモニターに設定することができる。
* WAFルール検出、拡張DLPルール（ヘッダー、URL、フルパケット）。Webアプリケーションポッドへのイングレス接続と、api-servicesへのアウトバウンド接続に使用され、apiセキュリティを強制する。
* WAF、DLP、アドミッション・コントロールのためのCRD。注：追加のクラスタ・ロール・バインディング/パーミッションが必要です。KubernetesとOpenShiftのデプロイのセクションを参照。CRDによるアドミッション・コントロールのインポート/エクスポートとバージョン管理。
* Rancher SSOの統合により、Rancher Managerから{product-name} コンソールを起動できる。この機能は、{product-name} コンテナが Rancher を介してデプロイされている場合にのみ利用できる。このデプロイはミラーリングされたRancherリポジトリ（例えばrancher/mirrored-neuvector-controller:5.0.0）からプルし、cattle-neuvector-system名前空間にデプロイします。注：2022年5月以降に更新されたRancherリリース2.6.5が必要で、現時点では管理者とクラスタ所有者の役割のみがサポートされています。
* RKE2での展開をサポート。
* プロキシを介したクラスタのフェデレーション（マルチクラスタマネージャ）のサポート。設定-> 構成でプロキシを構成し、フェデレーション接続を構成するときにプロキシを有効にします。
* 必要なrbacのclusterrole/bindingsを監視し、欠落があればイベントとUIで警告する。
* アドミッション・コントロール・ルールにおけるリソース制限の基準をサポートする。
* Microsoft Teams形式のWebhookをサポート。
* マップされたロールグループの下にAD/LDAPネストされたグループをサポート。
* IDP for Openshiftでclusterrolebindingsまたはrolebindings with group infoをサポート。
* ネットワークルールとアドミッションコントロールルールをFederatedルールに昇格できるようにする。

==== バグ修正

* ワーカーフェデレーションロールのバックアップが非フェデレーションクラスタにリストアされる問題を修正。
* セキュリティ・リスク-> 脆弱性における多数のCVEに対するページ読み込み時間の改善
* ユーザがPolicy-> Groupsメニューですべてのグループを選択したときに、モードを切り替えられるようにする。Nodesグループも選択されている場合は警告する。
* 同名のコンプライアンス・チェック項目を折りたたみ、展開可能にする。
* gRPC通信のセキュリティを強化する。
* 修正: rke2 セットアップで正しいワークロード特権情報を取得できなかった。
* openSUSE Leap 15.3 (k8s/crio) のサポートに関する問題を修正しました。

==== その他の最新情報

* HelmチャートのappVersionを5.0.0に、チャートのバージョンを2.2.0に更新。
* サーバーレススキャン機能/メニューを削除。
* Jfrog Xrayスキャン結果の統合サポートを削除しました（Artifactoryレジストリスキャンは引き続きサポートされます）。
* ECSでの展開のサポートは終了しました。アリノーンはまだECSにデプロイできるはずだが、手順や設定のドキュメントはサポートされていない。

=== {product-name} 4.xから5.xへのアップグレード（5.2.x以前）

[NOTE]
====
以下の手順は、5.0.xおよび5.1.xへのアップグレードに適用されます。5.2.xでは、サービスアカウントとバインディングが変更されたため、アップグレードを計画する際にxref:kubernetes.adoc#_deploy_suse_security[確認する]必要があります。
====


Helmユーザーの方は、{product-name} Helm chart 2.0.0以降にアップデートしてください。OpenShift上のOperatorまたはHelmのインストールを更新する場合は、以下の注記を参照してください。

. 古い neuvector-binding-customresourcedefinition クラスタロールを削除する。

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. neuvector-binding-customresourcedefinition clusterrole に新しい更新動詞を適用する。

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Kubernetes 1.19+用の古いcrdスキーマを削除する。

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Kubernetes 1.19+用の新しいcrdスキーマの作成

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. 新しいアドミッション、DLP、WAFクラスタロールとクラスタロールバインディングを作成する。

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Docker hub (docker.io) から{product-name} イメージを取得する際のイメージ名とパスを更新する。

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

{product-name}オプションとして、Helm チャート、デプロイメント yaml、configmap、スクリプトなどで{product-name} のライセンスとレジストリのシークレットへの参照を削除します。

*SCCおよびOperator/Helm経由でのアップグレードに関する注意事項*

特権SCCは、新しいデプロイメントでOperatorバージョン1.3.4以上でデプロイメントyamlに指定されたサービスアカウントに追加されます。{product-name} Operatorを以前のバージョンから1.3.4に、またはHelmを2.0.0にアップグレードする場合は、アップグレード前にPrivileged SCCを削除してください。

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== ベータ1版リリース 2022年4月

* グループ・モードの自動プロモーションを含む機能が完成。経過時間と基準に基づいてグループの保護モードをプロモートする。CRDが作成したグループには適用されない。この機能により、新しいアプリケーションを一定期間Discoverで実行し、動作を学習し、{product-name} 、NetworkとProcessの許可リストルールを作成し、その後自動的にMonitor、Protectモードに移行する。モニター基準への発見：グループ内の少なくとも1つのライブポッドのすべてのネットワークとプロセスのアクティビティを学習するための経過時間。保護するためのモニター当グループに設定された時間枠において、セキュリティイベント（ネットワーク、プロセスなど）は発生していない。
* Rancher 2.6.5のアプリとマーケットプレイスチャートをサポート。cattle-neuvector-systemネームスペースにデプロイし、Rancherから{product-name} へのSSOを可能にする。注：新しいチャートに更新するためには、Rancherからの以前のデプロイメント（例えば、パートナーカタログチャート、バージョン1.9.x以前）を完全に削除する必要があります。
* エンフォーサー、マネージャー、コントローラーのタグ：5.0.0-b1 (例：neuvector/controller:5.0.0-b1)

==== 2022年3月プレビュー.3リリース

[CAUTION]
.重要
====

CRD WAF、DLP、およびアドミッションコントロールの新機能用に以前のプレビューデプロイメントを更新するには、CRD yamlを更新し、新しいrbac/roleバインディングを追加してください：

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== 機能強化

* SUSE Linux (SLE, SLES) および Microsoft Mariner のスキャンをサポートします。
* ゼロドリフトのプロセスとファイル保護。これはプロセスとファイルの保護に関する新しいデフォルトモードである。ゼロ・ドリフトは、元のコンテナ・イメージの親プロセスに由来するプロセスのみを自動的に許可し、ファイルの更新や新規ファイルのインストールを許可しない。DiscoverまたはMonitorモードでは、zero-driftは不審なプロセスやファイルの活動に対して警告を発します。プロテクトモードでは、そのような活動をブロックする。ゼロドリフトでは、プロセスを学習したり、許可リストに追加したりする必要はない。グループのゼロドリフトを無効にすると、そのグループにリストされているプロセスとファイルのルールが代わりに有効になります。
* ネットワーク、プロセス、ファイルのための分割ポリシーモード保護。設定]-> [設定]で、ネットワークルールの実施に必要なネットワーク保護モードを個別に設定できるグローバル設定が追加されました。これを有効にすると (デフォルトは無効)、すべてのネットワーク ルールが選択された保護モード (検出、監視、保護) になり、プロセス/ファイル ルールはそのグループの保護モードのままになります (Policy-> Groups 画面に表示されます)。このようにして、ネットワークルールはプロテクト（ブロック）に設定し、プロセス/ファイルポリシーはモニターに設定することができる。
* WAFルール検出、拡張DLPルール（ヘッダー、URL、フルパケット）
* WAF、DLP、アドミッション・コントロールのためのCRD。注：追加のクラスタ・ロール・バインディング/パーミッションが必要です。KubernetesとOpenShiftのデプロイのセクションを参照。CRDによるアドミッション・コントロールのインポート/エクスポートとバージョン管理。
* Rancher SSOの統合により、Rancher Managerから{product-name} コンソールを起動できる。この機能は、{product-name} コンテナが Rancher を介してデプロイされている場合にのみ利用できる。注：更新されたRancherリリース（日付/バージョン未定）が必要です。
* RKE2での展開をサポート。
* プロキシを介したクラスタのフェデレーション（マルチクラスタマネージャ）のサポート。
* 必要なrbacのclusterrole/bindingsを監視し、欠落があればイベントとUIで警告する。
* アドミッション・コントロール・ルールにおけるリソース制限の基準をサポートする。

==== バグ修正

* ワーカーフェデレーションロールのバックアップが非フェデレーションクラスタにリストアされる問題を修正。

==== 2022年2月プレビュー.2リリース

* ソースのファイルおよびライセンスのマイナーな変更。

==== AWS ECSへのデプロイをサポート 非推奨

ECSでの展開のサポートは終了しました。アリノーンはまだECSにデプロイできるはずだが、手順や設定のドキュメントはサポートされていない。

=== 5.0「技術プレビュー」 2022年1月

==== 機能強化

* {product-name} 5.0オープンソース版の未サポート、「技術プレビュー」バージョンの最初のリリース。
* OWASPトップ10のサポートを追加し、WAFのようなルールで、ヘッダーや本文中のネットワーク攻撃を検出する。署名のCRD定義と適切なグループへの適用をサポート。
* サーバーレスのスキャン機能を削除。

==== バグ修正

* TBD

==== その他

* Helm chart v1.8.9が5.0.0のデプロイ用に公開されました。プレビュー版の5.0.0で使用する場合は、values.ymlに以下の変更を加える必要があります：
 ** レジストリをdocker.ioに更新する。
 ** Docker hubでイメージ名/タグをプレビュー版に更新する。
 ** imagePullSecretsは空のままにしておく
