= Notas de versão 5.x
:revdate: 2025-08-26
:page-revdate: {revdate}
:page-opendocs-origin: /14.releasenotes/01.5x/01.5x.md
:page-opendocs-slug:  /releasenotes/5x

== Notas de versão para 5.x

[NOTE]
====
Para receber notificações por e-mail sobre novos lançamentos, inscreva-se na lista de discussão da SUSE: https://lists.suse.com/mailman/listinfo/neuvector-updates
====

=== 5.4.6 Agosto de 2025

==== Novos recursos

* *NVSHAS-6733*: Exportar regras de resposta como CRD.
* *NVSHAS-9899*: NeuVector Process Profile Alerts for Java Services contém dados confidenciais.
* *NVSHAS-9990*: Adotar um novo algoritmo de hash para senhas de usuários.
* *NVSHAS-9968*: Suporte à configuração da senha padrão da conta de administrador.

==== Bugs corrigidos

* *NVSHAS-10062*: O gerenciador não exibe ERRO ao falhar na criação da senha de administrador durante o primeiro login.
* *NVSHAS-10041*: Falha na operação de federação "dados inválidos" ao configurar a federação por meio do ConfigMap.
* *NVSHAS-10018*: O Neuvector não está verificando todas as imagens no Registro do GitLab.
* *NVSHAS-10017*: Alerta de segurança falso positivo relacionado ao processo permitido.
* *NVSHAS-10001*: As imposições do Protect/Monitor "perduram" após a exclusão do grupo.
* *NVSHAS-9985*:    O NeuVector (Fed Master) cria um problema para todas as solicitações vindas de fora.
* *NVSHAS-9981*:    O Security Event é acionado sempre que uma nova "Process Profile Rule" é adicionada ou alterada em um grupo.

==== Avisos de segurança

* https://github.com/neuvector/neuvector/security/advisories/GHSA-8pxw-9c75-6w56[A conta de administrador tem uma senha padrão insegura]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-8ff6-pc43-jwv3[Gerenciamento de senhas inseguro e vulnerável a ataques de arco-íris]
* https://github.com/neuvector/neuvector/security/advisories/GHSA-w54x-xfxg-4gxq[Processos com argumentos sensíveis levam a vazamentos]

Consulte a documentação xref:cve.adoc[do Security Advisory e dos CVEs] para obter mais informações.

=== 5.4.5 Julho de 2025

==== Novos recursos

* *NVSHAS-9776*: Adicionar tolerância a etcd no gráfico do Helm.

==== Correções de bugs

* *NVSHAS-9507*: O contêiner OCI não está sendo escaneado.
* *NVSHAS-9787*: Remova o registro desnecessário do gerente.
* *NVSHAS-9788*: Refinar o algoritmo para gerar certificados.
* *NVSHAS-9789*: Remova o log desnecessário do gerenciador na configuração do registro remoto.
* *NVSHAS-9867*: O NeuVector mostra que `.NET Library System.Formats.Asn1 v8.013` afetou o CVE 2024-38095.
* *NVSHAS-9883*: [quay.io] Os filtros curinga não estão funcionando para o registro do Docker.
* *NVSHAS-9911*: A verificação do repositório usando a API REST resulta em uma "mensagem" incorreta.
* *NVSHAS-9930*: CVE-2018-20796 para `glibc/libc-bin : 2.36-9+deb12u10` - Falso positivo.
* *NVSHAS-9933*: O recurso adaptador de registro (Harbor) mostra erros no registro de destino durante a varredura.
* *NVSHAS-9934*: Suspeita de mau funcionamento da funcionalidade de desvio zero.
* *NVSHAS-9940*: Problema de modo de subdomínio do JFrog NV scan.
* *NVSHAS-9942*: As digitalizações de imagens de clientes estão falhando.
* *NVSHAS-9945*: Quando o nome do processo é muito longo, é difícil determinar como criar a regra de perfil de processo apropriada.
* *NVSHAS-9946*: Exibir problema com o alerta de controle de admissão para o tipo de credencial.
* *NVSHAS-9947*: [UI-ext] Gráfico de conformidade com status "Manual" ausente no Rancher NeuVector.
* *NVSHAS-9948*: Após a atualização para `5.4.3`, a configuração do NeuVector foi perdida.
* *NVSHAS-9949*: [Harbor][Usuário/pw incorreto] Ele ainda digitaliza imagens mesmo com a entrada incorreta de usuário/pw.
* *NVSHAS-9952*: Remova a "assinatura" do relatório de uso porque a NV não emite/verifica mais a chave de licença.
* *NVSHAS-9953*: O Pods Enforcer continua reiniciando.
* *NVSHAS-9954*: Exportador do NeuVector Prometheus gerando métricas duplicadas.
* *NVSHAS-9958*: A aplicação de regras de rede leva muito tempo.
* *NVSHAS-9960*: Os scanners não estão funcionando.
* *NVSHAS-9969*: Erro fatal: gravações simultâneas no mapa resultam na reinicialização do componente Enforcer.
* *NVSHAS-9971*: NV UI sobre `Get Bootstrap Password`.
* *NVSHAS-9975*: [Manager] TypeError: `this.mousemoveListener` não é uma função observada na GUI da NV.
* *NVSHAS-9986*: As regras de acesso a processos e arquivos não podem ser editadas ou removidas na visualização do grupo de políticas federadas.
* *NVSHAS-9988*: UI: As páginas de grupo não mostram todos os grupos quando mais de 2.000 grupos estão presentes.
* *NVSHAS-9991*: O grupo `nv.gatekeeper-controller-manager.openshift-azure-guardrails` está ausente da interface do usuário.
* *NVSHAS-9993*: Substitua MD5 por SHA256.
* *NVSHAS-9994*: O pod Enforcer continua reiniciando.
* *NVSHAS-9996*: O gráfico do timão deve permitir o modo não privilegiado dos pods do Enforcer.
* *NVSHAS-9998*: Não é possível exportar o grupo do NeuVector federated master.
* *NVSHAS-10000*: Atualize o NV para o BCI 15.7.
* *NVSHAS-10003*: A página de recarga não funciona na página autônoma da NV enquanto a interface do usuário do Rancher está aberta.
* *NVSHAS-10008*: Digitalização do registro - O menu Exibir não funciona para a imagem digitalizada.
* *NVSHAS-10010*: A inundação de TCP SYN bloqueia a entrada, resultando no bloqueio total do tráfego de entrada.

=== 5.4.4 Maio de 2025

==== Novos recursos

* **NVSHAS-9915**: Mostrar os resultados da varredura do módulo do scanner Harbor na interface do usuário do NeuVector.
* **NVSHAS-9904**: Exponha `imagePullPolicy` a `values.yaml` para cada componente.
* **NVSHAS-9869**: UI: Mova os controles de DDoS para o painel Grupo.
* **NVSHAS-9840**: [GCP] Suporte do NeuVector Autopilot para GCP.
* **NVSHAS-9248**: Exibir regras de processo/rede não utilizadas com contadores e registro de data e hora `Last Used`.
* **NVSHAS-8160**: [Controlador] Ajusta alguns itens para o cálculo da pontuação de risco de segurança.
* **NVSHAS-4673**: Sugestão para adicionar uma mensagem antes de exportar grupos.

==== Correções de bugs

* **NVSHAS-9931**: Adicionar um aviso se houver versões inconsistentes de produtos NeuVector em um multi-cluster.
* **NVSHAS-9925**: `/v1/scan/asset/images` API na página de registro falha.
* **NVSHAS-9913**: Problema com a exclusão de várias regras de rede relacionadas aos grupos Carga de trabalho:XYZ.
* **NVSHAS-9912**: Atualizar o Helm sobre algumas permissões RBAC do K8s necessárias para a conta de serviço do controlador.
* **NVSHAS-9909**: Mensagem "Signed Out - Go to loading page" exibida ao usar o NeuVector Rancher NavLink.
* **NVSHAS-9898**: Em um ambiente federado, a modificação dos critérios de um grupo fed.* criado pelo cliente (por exemplo, fed.core-systems) não funciona.
* **NVSHAS-9894**: [Enforcer] `Nv.protect` nega o comando de sondagem de prontidão do controlador `cat /tmp/ready`.
* **NVSHAS-9886**: A atividade de rede não resolve os nomes de domínio para as conexões de grupos externos personalizados.
* **NVSHAS-9884**: [Varredura de nó][Varredura de contêiner] A varredura falhará.
* **NVSHAS-9873**: Problema de pesquisa do filtro avançado da interface do usuário no NeuVector 5.4.2.
* **NVSHAS-9865**: As políticas de rede exportadas são diferentes, dependendo da ordem de seleção (mesmos grupos selecionados).
* **NVSHAS-9828**: [Enforcer: process] O NeuVector Enforcer não é capaz de detectar pods de curta duração (qualquer coisa com menos de 5 segundos).
* **NVSHAS-9783**: Depois de adicionar a política de rede para negar pacotes icmp, o NeuVector não vê nenhum alerta em `Security Events`.
* **NVSHAS-9176**: Mostrar um erro de script na página **Riscos de segurança > Vulnerabilidades** se uma permissão de usuário com a função de namespace `rt_scan:w` estiver conectada.

=== 5.4.3 Março de 2025

==== Novos recursos

* **NVSHAS-9793**: Permitir funções globais do Fed no LDAP/userinitcfg ao implantar o NeuVector por meio do ConfigMap e do Secret.
* **NVSHAS-9764**: [RFE] Adicionar suporte ao Azure para "Configuração de repositório remoto".
* **NVSHAS-9759**: Adicione os detalhes da data no Relatório de Ingresso-Exposição.
* **NVSHAS-9755**: Solicitação para exibir nomes de variáveis de ambiente juntamente com valores em alertas de segredos.
* **NVSHAS-9748**: [Helm] Atualização do NeuVector Helm para suporte à referência de nomes para grupos comuns em CRD (NVSHAS0-4717).
* **NVSHAS-9426**: Adicionar hostPath para o scanner ao gráfico do Helm.
* **NVSHAS-9326**: NeuVector - Módulo de scanner plugável Harbor.
* **NVSHAS-9835**: UI para desativar a verificação automática do nó.
* **NVSHAS-7997**: Conector de scanner para ghcr.io.
* **NVSHAS-7982**: Atribuir sensores WAF do Federation Master.

==== Correções de bugs

* **NVSHAS-9849**: Os aplicadores não se registram com os controladores.
* **NVSHAS-9847**: Os filtros curinga não funcionam no registro do Docker.
* **NVSHAS-9833**: A restauração da configuração falha nas implantações do Rancher.
* **NVSHAS-9832**: Problema com a criação de regras de rede usando o grupo de carga de trabalho.
* **NVSHAS-9821**: O nome do processo não corresponde à linha de comando do alerta da regra de lucro do processo.
* **NVSHAS-9817**: A criação do CRD do NvClusterSecurityRule mostra uma criação bem-sucedida, mas ele não foi realmente criado devido à duplicação de entradas de regras de processo.
* **NVSHAS-9812**: NeuVector prometheus-exporter métricas erradas.
* **NVSHAS-9811**: [Gerente] Não é possível acessar a GUI ao usar um certificado personalizado (CA) com CA raiz e CA intermediária no segredo.
* **NVSHAS-9801**: O modo FIPS + `manager.env.ssl=false` causa erro no Manager.
* **NVSHAS-9792**: Falha na sincronização da política de federação devido ao fato de o tamanho do corpo exceder o máximo do Consul.
* **NVSHAS-9784**: NeuVector retornando 404 durante a varredura do repositório de imagens Jfrog.
* **NVSHAS-9783**: Depois de adicionar a política de rede para negar pacotes icmp, o usuário não vê nenhum alerta em "Security Events".
* **NVSHAS-9780**: O NeuVector single sign on não está funcionando com o Rancher NavLink.
* **NVSHAS-9777**: Webhook JSON com chaves de "nível" duplicadas.
* **NVSHAS-9770**: A comutação automática após o modo Zero-Drift alterna a política incorreta.
* **NVSHAS-9765**: O acesso a arquivos não é totalmente bloqueado no modo de proteção.
* **NVSHAS-9756**: O Enforcer atingiu o máximo de CPU e tem vários alertas de pressão de memória.
* **NVSHAS-9668**: Falha no teste de conformidade no RKE2.
* **NVSHAS-9265**: Resultados incompletos e incorretos da varredura de vulnerabilidades no ambiente PRE PCI.
* **NVSHAS-9227**: A verificação do registro fica presa no meio do processo de verificação e vai para o estado "Ocioso".
* **NVSHAS-9729**: Uma contagem incorreta de vulnerabilidades é observada quando vários statefulset com o "mesmo nome" em namespaces são implantados em um projeto.
* **NVSHAS-9810**: O controlador NeuVector não está respondendo e a interface do usuário não está acessível.

=== 5.4.2 Janeiro de 2025

==== Novos recursos

* **NVSHAS-9726**: O monitor agora passa o URL do proxy.
* **NVSHAS-9719**: Anuncia a aposentadoria de certificados incorporados.
* **NVSHAS-9715**: Suporte ao valor do Helm Chart para configuração do nodeport no controlador e no gerenciador.
* **NVSHAS-9710**: Inclua uma coluna classificável `feed_rating` na guia **Vulnerabilidades**.
* **NVSHAS-9669**: Pontuação geral de segurança por meio da API REST.
* **NVSHAS-9590**: Capacidade de escolher qual pontuação de vulnerabilidade para todos os ativos.
* **NVSHAS-7555**: Incluir a opção "Auto Refresh" (Atualização automática) em Security Events (Eventos de segurança).

==== Correções de bugs

* **NVSHAS-9662**: Lógica inconsistente de Role/RoleBinding no Helm chart 2.8.2.
* **NVSHAS-9652**: Diferença observada no formato do syslog no splunk.
* **NVSHAS-9649**: O link do contêiner produz o código de resposta 404 no evento de segurança.
* **NVSHAS-9613**: NeuVector Manager Pod Error / NeuVector Web UI Indisponível.
* **NVSHAS-9507**: O contêiner OCI não está sendo escaneado.
* **NVSHAS-9443**: A atualização/instalação por meio do ArgoCD falha, pois não é possível criar o objeto leases.coordination.k8s.io.
* **NVSHAS-9436**: Possível falso negativo CVE em relação ao CVE-2024-7347.
* **NVSHAS-8386**: As chaves privadas e os certificados autoassinados ainda são enviados em várias imagens.
* **NVSHAS-9754**: [UI] Impedir que o usuário SSO relacionado ao Rancher desabilite a autenticação do OpenShift ou do RBAC do Rancher.
* **NVSHAS-9751**: [Proteção em tempo de execução] O Modo Monitor + Zero Drift não está gerando nenhum alerta quando um processo filho é executado.
* **NVSHAS-9721**: A interface do usuário deve exibir uma mensagem de erro apropriada quando o usuário inserir um nome de registro incorreto.
* **NVSHAS-9696**: Indicação inconsistente da cor dos ativos na página de vulnerabilidade.
* **NVSHAS-9686**: Espaço de nome codificado para o certificado do adaptador de registro no Neuvector Helm chart.
* **NVSHAS-9678**: Excesso de rastros de erro após a troca do linter.
* **NVSHAS-9670**: Gerente: Problema de aspas duplas na resposta de texto simples e problema de biblioteca java sem nome na execução do sbt.
* **NVSHAS-9667**: A configuração da variável de ambiente `CTRL_PATH_DEBUG` como erro na implantação do controlador não está funcionando.
* **NVSHAS-9665**: Regra de acesso a arquivos: A exclusão de regras predefinidas produz o erro "setRowData".
* **NVSHAS-9664**: Grupo de políticas: A exclusão do script personalizado produz "setRowData" TypeError.

[NOTE]
====
Os tipos padrão de gerenciador e serviço de adaptador de registro foram alterados para ClusterIP.  Os usuários ainda podem substituir a configuração substituindo `manager.svc.type` e `cve.adapter.svc.type` se preferirem o NodePort.
====

Na versão NeuVector 5.4.2, o suporte para implantações que usam o certificado interno incorporado foi descontinuado. O certificado encontrado em `/etc/neuvector/certs/internal` nas imagens do contêiner do NeuVector 5.4.2 será removido. Para continuar usando o NeuVector, os usuários devem:

==== 5.4.2 Nova instalação:

===== Usando o Helm:

- Ative os sinalizadores `internal.autoGenerateCert` e `internal.autoRotateCert` nos gráficos do Helm (eles serão ativados por padrão a partir da versão 5.4.2). Como alternativa, um método YAML está vinculado abaixo.

===== Usando YAML:

- Fornecer um xref:internal.adoc#_replacing_certificates_used_in_internal_communications_of_suse_security[certificado interno usando os métodos existentes].

==== Atualização de versões anteriores para a 5.4.2:

Crie e configure certificados internos do scanner para o controlador, o aplicador e o adaptador de registro para obter uma atualização contínua sem perder dados. Ainda assim, é recomendável fazer um backup de sua configuração antes de fazer o upgrade. 

As etapas a seguir só serão necessárias se a sua implementação usar um arquivo `.yaml`. A atualização usando o Helm não precisa dessas etapas adicionais, pois os certificados internos são criados por padrão por meio dos seguintes sinalizadores: `internal.autoGenerateCert` e `internal.autoRotateCert`.

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/ca.cert" > ca.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.pem" > tls.crt
----

[,shell]
----
docker run -it --entrypoint=bash neuvector/scanner:3.654 -c "cat /etc/neuvector/certs/internal/cert.key" > tls.key
----

[,shell]
----
kubectl create secret generic internal-cert -n neuvector  --from-file=tls.key --from-file=tls.crt --from-file=ca.crt
----

Exemplo de yaml 5.4.2 com certificado interno configurado:*https://github.com/neuvector/manifests/blob/main/kubernetes/5.4.0/neuvector-k8s.yaml* 

Informações adicionais sobre xref:internal.adoc[certificados internos].


No caso de uma configuração de PVC, os usuários podem configurar um PVC existente na nova instalação para restaurar uma configuração.


**Observação adicional para o scanner:**

Para os usuários atuais com versões anteriores à 5.4.2, o certificado permanecerá disponível no site `neuvector/scanner:latest` até 31 de março de 2025. Após essa data, ele será removido. Os usuários devem planejar o fornecimento do mesmo certificado interno para o controlador, o aplicador, o scanner e o adaptador de registro para continuar usando o scanner.

Observe que o scanner autônomo não será afetado por essas alterações.

=== 5.4.1 Novembro de 2024

==== Novos recursos

* **NVSHAS-8583**: Definição de modos de política granular para conjuntos de regras, modo de política de rede separado e modo de perfil em nível de grupo.
* **NVSHAS-9440**: Suporte ao modo de rede separado e ao modo de processo e arquivo no CRD.
* **NVSHAS-9369**: Adicione a categoria de registro de depuração por meio do suporte à implantação de helm para o controlador.
* **NVSHAS-9040**: Aprimora a mensagem do syslog quando a regra de controle de admissão é negada no modo monitor.

==== Correções de bugs

* **NVSHAS-9416**: [Scanner] activemq-all-5.8.0.redhat-60024.jar NÃO pode ser detectado com nenhum vul (mas a compilação anterior do scanner pode).
* **NVSHAS-9447**: Os pods do controlador/do scanner falham - "Saída de sistema não suportada".
* **NVSHAS-9278**: O CVE-2024-41110 foi encontrado na imagem mais recente do scanner.
* **NVSHAS-9467**: O grupo personalizado definido pelo rótulo do pod não propaga seus dados de perfil nos contêineres filhos.
* **NVSHAS-9442**: Problema de implantação no ArgoCD.
* **NVSHAS-9436**: Possível falso negativo CVE em relação ao CVE-2024-7347.
* **NVSHAS-9468**: Correção do CVE-2020-26160 para substituir o jwt-go pelo jwt:v5.
* **NVSHAS-9517**: O controle de admissão não é consistente, obtendo resultados incorretos.
* **NVSHAS-9532**: A varredura da imagem foi concluída, mas a implantação ainda não é permitida.
* **NVSHAS-9558**: Relatórios de expiração do token JWT http.StatusRequestTimeout 408.
* **NVSHAS-9576**: Limpe o campo de senha para dados de registro quando o usuário usar o modo de controlador com Jenkins para digitalizar.
* **NVSHAS-9425**: Crie nfq quando o contêiner tiver vxlan.
* **NVSHAS-9571**: [Registros] O filtro para todas as imagens digitalizadas não funciona bem.
* **NVSHAS-9589**: Clusters gerenciados desconectados - Incompatibilidade de versão com o cluster primário.
* **NVSHAS-8824**: O usuário não consegue excluir seus próprios grupos, não consegue criar grupos com escopo de namespace.
* **NVSHAS-9605**: O grupo de exportação com valores inválidos de modo de política e modo de perfil de processo é permitido por engano.
* **NVSHAS-9608**: O scanner não relata nenhum erro quando o controlador relata um erro para resultados de varredura enormes de ~23 MB.
* **NVSHAS-9534**: Erro de exibição nos controles de admissão.
* **NVSHAS-9600**: Não é possível desativar a depuração do controlador.
* **NVSHAS-9631**: Reduzir alguns erros do aplicador.
* **NVSHAS-9645**: Falha no processamento de CRDs pré-existentes.
* **NVSHAS-9592**: Nenhuma nova varredura, apesar da nova versão do banco de dados.
* **NVSHAS-9212**: Exibir mensagem de alerta em GET(/v1/eula) se a função neuvector-binding-secret(binding) estiver incorreta.
* **NVSHAS-9367**: Aprimore as mensagens de erro quando o registro não conseguir se conectar.
* **NVSHAS-9475**: A impressão da grade de fundo não é totalmente coberta quando o menu é recolhido.
* **NVSHAS-9485**: Mensagem incorreta para "Modo de política de segurança de rede" na interface do usuário.
* **NVSHAS-9480**: A UI da NV implantada no cluster downstream do Rancher gera HTTP/403 após o logout do Rancher.
* **NVSHAS-9547**: A classificação está quebrada na tabela de riscos de segurança --> vulnerabilidades.
* **NVSHAS-9570**: [Vulnerabilidades] Alterar a descrição da legenda para diferentes status nos ativos.
* **NVSHAS-9561**: A pontuação geral de segurança do painel de controle deve corresponder à pontuação real.
* **NVSHAS-9572**: [Vulnerabilidades] Os dados filtrados eram mantidos independentemente da atualização ou do novo login do usuário na página.
* **NVSHAS-9597**: A interface do usuário não responde a nenhum erro quando o controlador retorna 403 para POST(v1/group).
* **NVSHAS-8682**: O serviço de webhook do CRD precisa ser movido do helm chart do crd para o helm chart do aplicativo.

==== Problemas conhecidos

* Na versão 2.8.3 do gráfico, transferimos um recurso anteriormente alocado incorretamente do crds para o núcleo. Se você usar gráficos crds e core, poderá ter problemas durante a atualização se implantar o core primeiro. Para resolver esse problema, atualize primeiro os crds e depois os core charts.

=== 5,4 Setembro de 2024

* **Aprimoramentos da interface do usuário**: 
** Exibir usuários de SSO do Rancher.
** Gerenciar tokens JWT.
** Navegação aprimorada de imagens e links de resultados de varredura.
* **Aprimoramentos de segurança**: 
** Novos filtros de conformidade.
** Suporte para benchmarks CIS e assinatura de imagens OCI.
* **Rede e monitoramento**: 
** Rastreamento avançado de largura de banda e sessão.
** Monitoramento de DDoS.
** Suporte a várias redes.
* **Gerenciamento de certificados**: 
** Novas notificações para certificados internos que estão expirando, incluindo recursos de rotação.
* **Automação e integração**: 
** Automação da federação.
** Integração do Rancher RBAC.
** Controle de admissão aprimorado.
* **Desempenho e eficiência**: 
** Redução do uso de memória.
** Redução da taxa de dados do ISP.
** Exposição das estatísticas do cache do scanner.
* **Aprimoramentos de usabilidade**: 
** Suporte a senhas de bootstrap.
** Arquivamento de dados de faturamento na nuvem.
** Aplicação de limites de espaço de nome.

==== Novos recursos

* **NVSHAS-9012**: Exibição de usuários do Rancher SSO na interface de usuário da NV que têm o mesmo nome de usuário.
* **NVSHAS-8939**: Forneça uma opção na interface do usuário da NV para que os usuários da sessão SSO do Rancher possam descartar o token JWT atual (ou seja, fazer logout).
* **NVSHAS-7522**: Fácil navegação de imagens pelos registros.
* **NVSHAS-8148**: Link da imagem do contêiner para os resultados da varredura da imagem do registro.
* **NVSHAS-9258**: Adicionar uma nova notificação para certificados que estão expirando e certificados internos.
* **NVSHAS-8915**: Suporte para novos filtros de conformidade e relatório de conformidade.
* **NVSHAS-9403**: Filemonitor-UI: Permitir que o usuário exclua a regra predefinida do monitor de arquivos.
* **NVSHAS-8423**: Detectar largura de banda em nível de grupo, contagem de sessões ativas e violação da taxa de sessão com base nos limites configurados.
* **NVSHAS-9218**: Suporte para grupos federais e CRD para monitoramento de DDoS.
* **NVSHAS-8461**: Suporte a benchmarks do CIS para serviços gerenciados de k8s na nuvem.
* **NVSHAS-7664**: Reduzir as cobranças de dados do ISP durante a varredura do registro.
* **NVSHAS-8868**: Expor as estatísticas do cache do scanner.
* **NVSHAS-8676**: Aprimoramento do NV Protect para scripts de benchmark.
* **NVSHAS-9255**: Personalize os registros de pesquisa de controle de admissão para nomes de imagens sem FQDN.
* **NVSHAS-9144**: ID adicionado ao perfil de vulnerabilidade para facilitar a identificação.
* **NVSHAS-7687**: Suporte à configuração do nível de registro (debug/error/info/warn) para o enforcer e o controlador a partir da CLI.
* **NVSHAS-7518**: Altere os certificados internos dos componentes do site {product-name}.
* **NVSHAS-9287**: Habilite a rotação interna do pescoço.
* **NVSHAS-8562**: Adicionar notificação de expiração de certificado interno.
* **NVSHAS-8486**: Suporte à interface de rede Multus.
* **NVSHAS-7447**: Integração do Rancher RBAC com {product-name}.
* **NVSHAS-7822**: Automação da federação sem chamadas de API de script.
* **NVSHAS-8799**: Crie uma Estrutura de Conformidade para importar Modelos de Conformidade.
* **NVSHAS-8773**: Suporte à senha de bootstrap durante a implantação inicial.
* **NVSHAS-6740**: Aprimoramento do perfil de linha de base de desvio zero, impondo a lista aprendida no modo de proteção.
* **NVSHAS-8325**: Imponha o limite do namespace do contêiner para a regra de rede.
* **NVSHAS-8723**: Arquivar dados de faturamento da nuvem.
* **NVSHAS-9086**: Reduzir o uso da memória do processo do controlador, eliminando a estrutura de dados vulTrait.
* **NVSHAS-6979**: Capacidade de incluir comentários sobre a regra de resposta no conteúdo do alerta.
* **NVSHAS-8845**: Criar APIKEY com função FedReader e FedAdmin.
* **NVSHAS-9306**: A avaliação da configuração do Admission Control mostra o ID da regra responsável pelas implementações permitidas ou negadas.
* **NVSHAS-9078**: Suporte à assinatura de imagens para imagens OCI.
* **NVSHAS-7945**: Suporte ao benchmark DISA STIG para Kubernetes.
* **NVSHAS-8234**: Controle de admissão Lógica que permite imagens que deveriam ser negadas.

==== Correções de bugs

* **NVSHAS-9005**: TypeError em registros: Não é possível ler propriedades indefinidas (lendo 'total_records').
* **NVSHAS-9085**: O relatório Assets View PDF mostra 0% de vulnerabilidade, mesmo com as vulnerabilidades existentes.
* **NVSHAS-9084**: O relatório Assets View PDF mostra NaN quando a lista de imagens está vazia.
* **NVSHAS-9128**: Eventos de segurança: O contêiner não poderá ser exibido se não houver um valor de namespace da carga de trabalho.
* **NVSHAS-9025**: Escopo de aceitação de vulnerabilidade Neuvector para contêineres.
* **NVSHAS-9155**: Nome de coluna incorreto da imagem de digitalização do registro e nome de arquivo ausente
* **NVSHAS-9122**: O Neuvector Master faz logout a qualquer momento ao usar "Multiple Cluster" com login SSO do Rancher.
* **NVSHAS-9266**: Verificação do registro: O botão Scan Report by Layer deve estar oculto ou desativado quando não houver vulnerabilidade.
* **NVSHAS-9219**: Permitir que os usuários ativem a validação do certificado do servidor para servidores de autenticação.
* **NVSHAS-9246**: A filtragem para exportação CSV/PDF não funciona.
* **NVSHAS-8947**: Não é possível importar a configuração de NV quando autenticado por meio do Rancher SSO.
* **NVSHAS-9282**: UI: A edição da entrada de registro do OpenShift falha devido à falta de um token.
* **NVSHAS-9098**: Aprimore a experiência do usuário no carregamento de páginas de risco.
* **NVSHAS-9267**: Não permita que a interface do usuário no cluster mestre 5.4 alterne para clusters gerenciados anteriores ao 5.4 devido a alterações na API REST.
* **NVSHAS-9285**: UI: O botão da lista suspensa se sobrepõe a outros elementos.
* **NVSHAS-9302**: Não é possível criar APIKEY com função FedReader e FedAdmin.
* **NVSHAS-8539**: Reconfigurar a definição de proxy perde a senha.
* **NVSHAS-9293**: Remoção de detalhes de imagens não relacionadas nos relatórios de vulnerabilidade.
* **NVSHAS-9238**: A interface do usuário não atualiza o nome do cluster exibido depois que ele é alterado.
* **NVSHAS-9363**: A grade Notification Configuration > Webhooks não está alinhada corretamente.
* **NVSHAS-9362**: O filtro Security Risk Vulnerabilities retorna 0 resultados.
* **NVSHAS-8699**: Não é possível distinguir o usuário se o usuário do Rancher AD for o mesmo.
* **NVSHAS-9062**: Exibição de usuários do Rancher SSO na UI da NV que têm o mesmo nome de usuário (Conversão no controlador).
* **NVSHAS-9071**: Alguns módulos não são relatados apenas na varredura de contêineres.
* **NVSHAS-8242**: Chamada gRPC para testar se o controlador lida com a gravidade crítica.
* **NVSHAS-8908**: Analisar o X-Forwarded-Port considerando corretamente o separador de vírgula.
* **NVSHAS-9024**: AdmissionControl Perf. de função de risco
* **NVSHAS-9091**: Não foi possível relatar todos os módulos sob as fontes ol:9.1, photon:5.0, rhel:9.1 e amzn:2023 na verificação de repositório, registro e autônoma.
* **NVSHAS-8997**: Reduzir consideravelmente o número de slots de política por nó para melhorar o desempenho.
* **NVSHAS-9059**: Grupos CRD visíveis em NV mesmo após a exclusão de K8s.
* **NVSHAS-9107**: Falha de goroutine em rest.handlerConfigLocalCluster.
* **NVSHAS-9108**: A porta 18500 não deveria estar aberta.
* **NVSHAS-9119**: Falha de rotina em probe.(*FileNotificationCtr).AddContainer().
* **NVSHAS-9125**: Não deve ser permitida a criação de registros CRD com configurações inválidas.
* **NVSHAS-9124**: Docker: muitos incidentes inesperados do processo de verificação de integridade são relatados.
* **NVSHAS-9111**: A NV deve consultar o site `--event-qps > 0`.
* **NVSHAS-9130**: Incidentes inesperados de Container.Package.Updated são encontrados depois que um contêiner específico é iniciado.
* **NVSHAS-9080**: O usuário do leitor federal não consegue acessar algumas APIs REST.
* **NVSHAS-9092**: O usuário com espaço de nome não deve ver os ativos globais.
* **NVSHAS-9116**: O cluster de trabalho poderá sair se a conexão for interrompida.
* **NVSHAS-8980**: Obtenha o host e a interface de túnel no nó com sucesso no oc 4.15.
* **NVSHAS-9188**: Definir a interface mgmt-br como interface de host para o nó harvester.
* **NVSHAS-4858**: Não expandir o grupo de contêineres no controlador para melhorar o desempenho da implementação de políticas e reduzir o uso de CPU e memória.
* **NVSHAS-8700**: Às vezes, o usuário do Rancher AD não consegue fazer login em {product-name}.
* **NVSHAS-9121**: A configuração do Limite de monitoramento de rede do grupo não pode ser editada.
* **NVSHAS-9189**: A varredura ficará presa no agendamento depois que o controlador for desligado e reiniciado.
* **NVSHAS-9019**: Corrige o estado de link não sincronizado da interface do host.
* **NVSHAS-8305**: Remover o certificado incorporado.
* **NVSHAS-9013**: Remoção do filtro BPF no monitor de processo.
* **NVSHAS-7853**: EOF do handshake TLS.
* **NVSHAS-9290**: A regra de perfil de processo adicionada pelo usuário não está tendo efeito com o ZD ativado.
* **NVSHAS-9301**: A NV implantada no Rancher Prime não consegue distinguir o sabor do Rancher.
* **NVSHAS-9289**: Permitir upgrade quando o RBAC estiver ausente.
* **NVSHAS-7601**: Melhorar a restauração do backup de configuração do PV durante os cenários.
* **NVSHAS-7687**: Adicionar configuração de nível de syslog para o enforcer.
* **NVSHAS-9292**: A exposição Fix Ingress Egress mostra 0 vulnerabilidades.
* **NVSHAS-9270**: Suporte a k3s para o pipeline de benchmark do CIS.
* **NVSHAS-9338**: Alerta "O cluster gerenciado [id] está desconectado do primário".
* **NVSHAS-9358**: A varredura de imagens usando proxy falharia.
* **NVSHAS-9337**: Enviar mensagem de registro quando for detectada inundação SYN.
* **NVSHAS-9209**: Exclua o cache de domínio quando o namespace for excluído do k8s.
* **NVSHAS-8985**: Os registros federados desaparecem após a reinicialização do controlador.

==== Problema conhecido:

* **NVSHAS-9443**: A atualização/instalação por meio do ArgoCD falha, pois não é possível criar o objeto leases.coordination.k8s.io.
* **Solução alternativa**: Crie os objetos de arrendamento fornecidos antes de fazer upgrade para a versão 5.4.0 usando o CD do ARGO. Altere o namespace se ele for diferente de neuvector.
+
--
[,bash]
----
cat <<EOF | kubectl apply -f -
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-controller
  namespace: neuvector
spec:
  leaseTransitions: 0
---
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: neuvector-cert-upgrader
  namespace: neuvector
spec:
  leaseTransitions: 0
EOF
----
--

=== 5.3.4 Julho de 2024

==== Correções de bugs

* As interfaces `host` e `tunnel` são recuperadas com sucesso com o OpenShift CLI v4.15.
* O intervalo de IPs 169.254.x.x é excluído dos IPs da interface do host.
* Examine novamente a interface do host após 1 minuto de inicialização do enforcer.
* Foi corrigido um problema em que o regex do URL do emissor do OpenID estava falhando.
* Corrige os seguintes CVEs:
+
|===
| CVE | Aplica-se a | Impacto

| CVE-2023-42364
| caixa ocupada
| {CVE-medium}

| CVE-2023-42365
| caixa ocupada
| {CVE-medium}

| CVE-2024-6197
| enrolar
| {CVE-medium}

| CVE-2024-6874
| enrolar
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.2.4-s5 Julho de 2024

* Corrige os seguintes CVEs:

|===
| CVE | Aplica-se a | Impacto

| CVE-2023-42363
| caixa ocupada
| {CVE-medium}

| CVE-2023-42364
| caixa ocupada
| {CVE-medium}

| CVE-2023-42365
| caixa ocupada
| {CVE-medium}

| CVE-2023-42366
| caixa ocupada
| {CVE-medium}

| CVE-2024-6197
| enrolar
| {CVE-medium}

| CVE-2024-6874
| enrolar
| {CVE-medium}

| CVE-2024-5535
| openssl
| {CVE-critical}

| CVE-2024-4603
| openssl
| {CVE-medium}

| CVE-2024-4741
| openssl
| {CVE-medium}
|===

=== 5.3.3 Junho de 2024

==== Aprimoramentos

* Permitir que os usuários bloqueiem o uso de classes de armazenamento específicas na página `Admission Controls`.
* O site `LDAP Authentication` tem campos separados para a configuração de `baseDN` e `groupDN`.
* O site `Egress and Ingress chart` tem uma nova coluna de vulnerabilidade que contém a contagem de vulnerabilidades `High` e `Medium` para cada serviço.

==== Correções de bugs

* Corrigido o erro relacionado a `regex` ao usar uma vírgula (`,`) em uma entrada múltipla `Admission Control user criteria`.
* Foi corrigido o erro que fazia com que a verificação de CVE dos pacotes `jar` não mostrasse todos os pacotes afetados por um mesmo CVE. Agora todas as ocorrências são relatadas.
* Corrige os seguintes CVEs:

|===
| CVE | Aplica-se a | Impacto

| CVE-2024-35195
| python:requests
| {CVE-medium}

| CVE-2024-21011
| openjdk11
| {CVE-low}

| CVE-2024-21012
| openjdk11
| {CVE-low}

| CVE-2024-21068
| openjdk11
| {CVE-low}

| CVE-2024-21085
| openjdk11
| {CVE-low}

| CVE-2024-21094
| openjdk11
| {CVE-low}
|===

==== Outros

* Permitir que os usuários definam recursos para `updater-cron-job` ao instalar o {product-name} com o gráfico Helm.
* Revisão e dissociação do controle de versão do contêiner do exportador Prometheus para o controle de versão do `controller`.
* (Scanner) Detecta o pacote/módulo `R` no Ubuntu e no Red Hat Enterprise Linux.
* (Scanner) Adicionado suporte à verificação do PHP Composer.

=== 5.2.4-s3 Abril de 2024

* Corrige os seguintes CVEs:

|===
| CVE | Aplica-se a | Impacto

| CVE-2021-40633
| giflib
| {CVE-high}

| CVE-2023-48161
| giflib
| {CVE-high}

| CVE-2024-28757
| expatriado
| {CVE-high}

| CVE-2023-39742
| giflib
| {CVE-medium}

| CVE-2023-45288
| go:golang.org/x/net
| {CVE-medium}

| CVE-2024-25629
| c-ares
| {CVE-medium}

| CVE-2024-3651
| python:idna
| {CVE-medium}

| CVE-2024-2511
| openssl
| {CVE-low}
|===

=== 5.3.2 Abril de 2024

==== Correções de bugs

* Após o upgrade para a versão 5.3.1 de uma versão anterior do site {product-name}, os recursos personalizados pré-existentes do NvClusterSecurityRule podem ser excluídos inadvertidamente. OBSERVAÇÃO: A versão 5.3.1 foi removida do hub do docker para evitar o problema de atualização.

=== 5.3.1 Abril de 2024

[IMPORTANT]
====
A versão 5.3.1 foi removida do hub do docker para evitar o problema de atualização corrigido na versão 5.3.2. Use a versão 5.3.2.
====

==== Aprimoramentos

* Permita que os usuários definam as vulnerabilidades do '`accepted`' ao usar as ações do Github para que elas não afetem os fluxos de trabalho.
* Adicione os filtros Gravidade, Nível de pontuação e Classificação do feed à visualização Ativos > Registro > Vulnerabilidades de imagem.
* Permite, ao configurar um registro, se ele deve usar o proxy definido para as varreduras de imagem do registro.

==== Correções de bugs

* Riscos de segurança > Vulnerabilidades > O filtro avançado não filtra "CVE sem correção
* Violação inesperada do contêiner para o contêiner no modo de host
* Aceitar o formato de imagem OCI ao mudar para o docker api 1.24
* A Verificação do Registro não deve verificar artefatos que não sejam de imagem / não deve registrar um erro
* Permitir a verificação de assinatura de imagem de par de chaves sem raiz, sem depender da Internet ou da sigstore.
* Os eventos de segurança não são permitidos pelas regras de rede em um nó específico (relacionado às mensagens de erro "Container Task chan full")
* O contêiner não pode ser adicionado à carga de trabalho com êxito (ocorrências frequentes). Resultante de deadlock de mensagens de canal.

==== Outros

* Atualize os plug-ins de scanner para Jenkins, GitHub action e Bamboo.
* (Scanner) Aceita o formato de imagem OCI ao mudar para o docker api 1.24.
* (Scanner) A Verificação do Registro não deve verificar artefatos que não sejam de imagem / não registrar um erro.
* (Scanner) Adicionar suporte à verificação do compositor php.

==== {product-name} Extensão da interface do usuário v. 1.0 para o Rancher Março de 2024

* Após a instalação do {product-name}, a xref:rancher.adoc#_suse_security_ui_extension_for_rancher[ativação/instalação] da extensão da interface do usuário {product-name} do Rancher exibirá um painel para o cluster, incluindo links para o SSO do cluster {product-name} completo. OBSERVAÇÃO: A extensão pode ser exibida como de terceiros, o que será corrigido em uma versão futura. Além disso, após a instalação, os usuários do Rancher 2.7.x podem ver dois ícones {product-name} UI Ext na lista (bug). Um ícone indicará Uninstall (o que significa que está instalado) e o outro deverá indicar Install. Isso pode ser deixado como está, ou seja, não instalar novamente se a extensão já estiver instalada.

=== 5.2.4-s2 Fevereiro de 2024

* Corrige os seguintes CVEs:
* Alta cve: CVE-2023-52425 no expat, CVE-2024-20952 e CVE-2024-20918 no openjdk11
* Med cve: CVE-2023-52426 em expat, CVE-2024-20926, CVE-2024-20921, CVE-2024-20945 e CVE-2024-20919 em openjdk11, CVE-2024-0727 e CVE-2023-6237 em openssl

=== 5.3.0 Fevereiro de 2024

==== Aprimoramentos

* Mostrar URLs de destino externo (FQDN) nos relatórios Dashboard (saída), PDF e CSV, bem como na tela Network Activity e nas listas Security Events (violações)
* No modo Discover, aprende automaticamente as saídas para grupos de endereços FQDN externos. Um novo grupo personalizado de FQDN externo será criado, a menos que a conexão externa corresponda a uma regra existente.
* Habilite o aprendizado (modo Discover) e o bloqueio (modo Protect) de ICMP por meio da nova variável de ambiente do Controlador CTRL_EN_ICMP_POLICY = 1
* Exporte CRDs para o Github para oferecer suporte a gitops em um repositório padrão usando o console ou a API REST.
* Suporte ao logout único do SAML SSO com o ADFS iDP
* Adicionar suporte à plataforma ARM64. A extração de plataformas baseadas em ARM extrairá automaticamente as imagens apropriadas do ARM64 {product-name}.
* Suporte a webhooks por meio de um proxy
* Aprimorar a função de auditoria do controle de admissão para incluir os resultados de todas as regras. Lista o resultado de cada regra e adiciona outra entrada para a ação final que ocorreria quando avaliada em uma implementação de controle de admissão em tempo real.
* Aplicar regras de controle de admissão desativadas via CRD ou yaml (kubectl)
* Exportação/importação do perfil de vulnerabilidade por meio do console, CRD ou API REST. A importação substituirá o perfil existente. A exclusão do CRD resultará em um perfil vazio.
* Exportação/importação de modelos de perfis de conformidade por meio do console, CRD ou API REST. A importação substituirá o modelo existente.
* Adicione um status "Manual" nos relatórios de conformidade para benchmarks do CIS que devem ser executados manualmente pelos usuários (não executados por {product-name}).
* Melhorar o carregamento/desempenho da interface do usuário da página Vulnerabilidades
* Unificar o login da sessão do navegador. Com isso, todas as guias do navegador compartilham a mesma sessão de login, a abertura de uma nova guia a partir de uma sessão existente não solicita credenciais e, quando uma guia é desconectada, todas as guias são desconectadas.
* Aprimoramentos na segurança do console (UI): 1) adicionar cabeçalhos de segurança obrigatórios (X-Content-Type-Options nosniff; X-XSS-Protection 1; mode=block; X-Frame-Options SAMEORIGIN; Cache-Control private, no-cache, no-store, must-revalidate HTTP Strict Transport Security max-age=15724800, 2) adicionar cabeçalho CSP (por exemplo, definir uma diretiva '`default-src`' ), 3) remover a divulgação do nome do servidor
* Suporte a versões mais recentes dos benchmarks do CIS. Kubernetes (1.8.0), Kubernetes V1.24 (1.0.0), Kubernetes V1.23 (1.0.1), RedHat OpenShift Container Platform (1.4.0)
* Mostrar em Assets -> Containers -> Detalhes dos containers que foram verificados nos registros em relação ao tempo de execução
* Adicionar link para o grupo no pop-up Riscos de segurança -> Vulnerabilidades -> Impacto para editar facilmente o modo de grupo
* Suporte a links diretos em URLs para imagens e/ou páginas de vulnerabilidade de contêineres
* Adicione a opção de redefinição de senha para que o administrador redefina a senha do usuário nas configurações do console -> Users
* Permita o envio de registros de eventos para os registros do pod do controlador em Settings -> Configuration -> Notification. Os eventos enviados começarão com "notification=" e serão salvos somente no pod do controlador líder. Observe que há um erro nesta versão em que, para alterar o nível do evento, o SYSLOG deve estar ativado (e pode ser desativado, se desejado, após a alteração do nível).
* Remover o requisito para que o controlador/forçador monte "/host/cgroup".
* Adicionar o menu Obter suporte com links para o Slack, documentação e outros recursos
* Preencher o campo de mensagem em /v1/log/activity logs

==== Correções de bugs

* Erro interno do servidor em Riscos de segurança -> Vulnerabilidades com um grande número de CVEs
* SIGSEGV: violação de segmentação no controlador
* A exclusão de arquivos vulneráveis (por exemplo, jar) não é removida da lista de vulnerabilidades
* Certificado Syslog inválido usando o algoritmo de assinatura SHA256withECDSA
* {product-name} mostra eventos de segurança que devem ser permitidos por uma regra de rede
* Nó não gerenciado com executor "zumbi" em execução
* O filtro avançado mostra os campos Remediation e Impact em branco
* Correção do tratamento de strings para evitar a reinicialização inesperada do Enforcer
* Violações inesperadas relacionadas a grupos incorporados
* A chamada RPC de depuração do Support-bundle enforcer para dados retorna erro
* O grupo não está correspondendo aos eventos de segurança
* Enviar eventos para o Slack não está funcionando - com proxy
* Exibição de eventos de segurança para regras de rede permitidas

==== Outros

* Adicionar detecção automática do mecanismo de contêiner (socket) em tempo de execução ao gráfico do Helm
* Remova a configuração para executar o controlador em modo privilegiado no gráfico Helm e o requisito para que o controlador/enforcer monte "/host/cgroup".
* Os arquivos de implantação do kubernetes de amostra foram removidos dos documentos do site {product-name}. Consulte o link para ver exemplos.

==== Alterações destacadas que podem exigir alterações para implementações manuais (todas as alterações já estão refletidas no gráfico mais recente do Helm para a versão 5.3.x)

* A detecção automática do tempo de execução do contêiner (soquete) elimina a necessidade de especificar o tempo de execução do contêiner e o caminho do soquete.
* A remoção do requisito de executar o controlador em modo privilegiado remove a necessidade de montar o soquete de tempo de execução e montar /host/cgroup/
* Adicionada vinculação de função/função para neuvector-binding-secret, bem como neuvector-secret em yaml.
* Novas contas de serviço e associações de funções necessárias para a versão 5.3
* Todos os arquivos yaml de implantação referenciados agora têm /5.3.0/ em seus caminhos

=== 5.2.4-s1 Janeiro de 2024

==== Liberação de patches de segurança

* Corrige o CVE-2023-6129 no openssl e o CVE-2023-46219, CVE-2023-46218 no curl.

=== 5.2.4 Novembro de 2023

==== Correções de bugs

* Alterações de validação de Azure AKSWebhookConfiguration e registro de erros.

=== 5.2.3 Novembro de 2023

==== Aprimoramentos

* Adicionar suporte à API 2.0 do NVD no scanner.
* Faça a varredura do host do contêiner no modo autônomo do scanner.

[,shell]
----
docker run --rm --privileged --pid=host neuvector/scanner -n
----

==== Correções de bugs

* A varredura em um nó falha devido a um problema de bloqueio de docker cp / grpc.

=== 5.2.2-s1 Outubro de 2023

==== Atualização de segurança

* Atualize os pacotes para corrigir os CVEs, incluindo o High CVE-2023-38545 e o CVE-2023-43804.

=== 5.2.2 Outubro de 2023

==== Aviso de segurança para CVE-2023-32188

* Corrija o CVE-2023-32188 "`JWT token compromise can allow malicious actions including Remote Code Execution (RCE)`" gerando automaticamente o certificado usado para assinar o token JWT na implantação e atualização, e gerando automaticamente o certificado da API Manager/RESTful durante as implantações baseadas no Helm.
 ** O certificado para assinatura JWT é criado automaticamente pelo controlador com validade de 90 dias e rotacionado automaticamente.
 ** A geração automática do certificado do gerenciador, da API REST e do adaptador de registro requer o uso de uma instalação baseada no Helm usando {product-name} helm versão 2.6.3 ou posterior.
 ** O certificado integrado ainda é usado para implantações baseadas em yaml se não for substituído durante a implantação; no entanto, é recomendável substituí-lo (consulte a próxima linha).
 ** xref:replacecert.adoc[A substituição] manual xref:replacecert.adoc[do certificado] ainda é suportada e recomendada para versões anteriores ou implementações baseadas em yaml. Consulte o aviso de segurança do GitHub {product-name} https://github.com/neuvector/neuvector/security/advisories/GHSA-622h-h2p8-743x[ aqui] para obter uma descrição.
 ** O uso de certificados fornecidos pelo usuário ainda é suportado como antes para implantações baseadas em Helm e yaml.
* Adicione controles adicionais em scripts de conformidade personalizados. Por padrão, agora não é permitido adicionar scripts personalizados, a menos que a variável de ambiente CUSTOM_CHECK_CONTROL seja adicionada ao Controller e ao Enforcer. Os valores são "disable" (padrão, não permitido), "strict" (somente função de administrador) ou "loose" (funções de administrador, conformidade e política de tempo de execução).
* Evitar injeção de LDAP - o campo de nome de usuário é escapado.

==== Aprimoramentos

* Adicionar dados de varredura adicionais aos resultados de CVE enviados pelo SYSLOG para varreduras em camadas
* Suporte à API 2.0 do NVD para escanear o banco de dados CVE
* Forneça a data de compilação da imagem do contêiner em Assets -> Detalhes do contêiner
* Ajustar a classificação das regras de rede: desative a classificação na visualização de regras de rede, mas ative a classificação das regras de rede na visualização de grupo.
* Ativar/desativar a detecção/alerta de TLS 1.0 e TLS 1.1 com variáveis de ambiente para o Enforcer THRT_SSL_TLS_1DOT0, THRT_SSL_TLS_1DOT1. Desativado por padrão.
* Adicione a variável de ambiente AUTO_PROFILE_COLLECT ao Controller e ao Enforcer para ajudar a capturar o uso da memória ao investigar eventos de pressão de memória. Defina o valor = 1 para ativar.
* As avaliações de configuração do Controle de Admissão devem mostrar todas as violações com uma única varredura.
* Adicionar mais opções para os critérios do relatório CVE nas Regras de Resposta. Exemplo 1 - "cve-high-with-fix:X" significa: Quando o número de (vulnerabilidades altas que foram corrigidas) >= X, acione a regra de resposta. Exemplo 2 - "cve-high-with-fix:X/Y" significa: Quando o número de (vulnerabilidades altas que foram relatadas há Y dias e foram corrigidas) >= X, acione a regra de resposta.

==== Correções de bugs

* A exportação da política de grupo não retorna nenhum conteúdo YAML real
* Aprimorar a poda de namespaces com função dedicada
* {product-name} O usuário do namespace não pode ver os ativos-->namespaces
* Ignorar o tratamento das solicitações CRD CREATE/UPDATE se o namespace do CR já tiver sido excluído
* Fornecer solução alternativa para parte dos grupos CRD que não podem ser removidos com êxito depois que os namespaces são excluídos.

=== 5.2.1 Agosto de 2023

==== Aprimoramentos

* Relatar resultados de varredura em camadas e dados CVE adicionais em mensagens SYSLOG. Isso é ativado por meio de uma caixa de seleção em Settings -> Configuration -> SYSLOG
* Exportar mapeamentos NIST 800-53 (para benchmarks CIS do docker) no relatório de conformidade csv exportado
* Suporte à configuração de proxy na verificação de assinatura de imagem
* Incluir o resultado da verificação de assinatura de imagem no relatório de CVE baixado
* Suporte a anotações de pod para políticas de controle de admissão, disponíveis por meio dos critérios personalizados
* Adicionar o campo Última modificação para filtrar a impressão de relatórios de vulnerabilidades, bem como o filtro avançado na visualização de vulnerabilidades

==== Correções de bugs

* Não crie um administrador padrão com senha padrão na implantação inicial do {product-name} para a oferta de faturamento da AWS (adaptador CSP), exigindo que o usuário use um segredo para criar o nome de usuário e a senha do administrador
* Corrigir o arquivo .json que aumentava de tamanho e travava um nó do kubernetes
* Aprimorar a lógica de detecção de injeção de SQL
* Ao instalar o helm crd chart antes de instalar o {product-name} core chart, as contas de serviço estão ausentes
* O resultado da conformidade da varredura de imagem I.4.1 está incorreto
* Relatório de filtro avançado de vulnerabilidade mostrando imagens de todos os outros namespaces

=== 5.2.0 Julho de 2023

==== Aprimoramentos

* Suporte a tokens para acesso à API {product-name}. Consulte Configurações -> Usuário, Chaves de API... para criar uma nova chave de API. As chaves podem ser definidas para funções padrão ou personalizadas.
* Suporte ao faturamento PAYG do AWS Marketplace para assinaturas de suporte mensal {product-name}. Os usuários podem assinar o {product-name} pelo suporte do SUSE, cobrado mensalmente em sua conta do AWS com base no uso médio da contagem de nós do mês anterior. Detalhes https://open-docs.neuvector.com/deploying/awsmarketplace[aqui].
* Suporte à assinatura de imagens para controles de admissão. Os usuários podem exigir que o {product-name} verifique se as imagens são assinadas por partes específicas antes de serem implantadas no ambiente de produção, por meio de uma integração com o Sigstore/Cosign. Consulte Assets -> Sigstore Verifiers para criar novos assets de assinatura. As regras podem ser criadas com critérios de Image Signing e/ou Image Sigstore Verifiers.
* Habilite cada regra de controle de admissão para ter seu próprio modo de Monitorar ou Proteger. Uma ação de negação no modo Monitor alertará, e uma ação de negação no modo Protect bloqueará. As ações de permissão não são afetadas.
* Adicione um novo operador regex em Política > Controle de admissão > Adicionar regra para usuários e grupos de usuários para oferecer suporte a regex. Operadores de suporte "corresponde a QUALQUER regex em" e "corresponde a NENHUM regex em".
* Adicionar suporte a critérios de controle de admissão, como limites de recursos. Um novo critério foi adicionado para Limites de recursos, e critérios adicionais são suportados por meio das configurações de Critérios personalizados.
* Suporte à invocação do scanner {product-name} a partir dos registros do Harbor por meio da interface https://github.com/goharbor/pluggable-scanner-spec[de scanner conectável]. Isso requer a configuração da conexão com o controlador (API exposta). O adaptador Harbor chama o endpoint do controlador para acionar uma varredura, que pode ser feita automaticamente por push. Os serviços de interrogatório podem ser usados para varreduras periódicas. Os resultados de varredura dos controladores Federation Primary SÃO propagados para clusters remotos.  OBSERVAÇÃO: Há um problema com o erro do ponto de extremidade do adaptador baseado em HTTPS: ignore o erro Test Connection (Teste de conexão), pois ele funciona mesmo que seja exibido um erro (ignore a validação do certificado).
* Serviço SaaS pesquisável para pesquisas de CVE. Pesquise o banco de dados mais recente do {product-name} CVE para ver se existe um CVE específico no banco de dados. Esse serviço está disponível para clientes do {product-name} Prime (assinatura de suporte pago). Entre em contato com o suporte por meio do portal da SCC para obter acesso.
* Permitir que o usuário desative a proteção de rede, mas mantenha o WAF/DLP funcionando. Configure o Network Policy Enablement em Settings -> Configuration.
* Use contas de serviços menos privilegiadas conforme necessário para cada componente do site {product-name}. Uma variável "`leastPrivilege`" é introduzida. O padrão é false. OBSERVAÇÃO: O uso do gráfico de leme atual com essa variável em uma versão anterior à 5.2.0 não funcionará corretamente.
* Vincule-se a uma conta de serviço não padrão para atender à recomendação do CIS 1.5 5.1.5.
* Permita que o administrador configure o tempo limite de sessão padrão do usuário em Settings -> Users, API Keys & Roles.
* Banner de login personalizável e texto de cabeçalho da interface do usuário personalizável para implantações regulamentadas e governamentais. Os requisitos para a configuração podem ser encontrados xref:customui.adoc[aqui].
* Suporte do SYSLOG para transporte criptografado TLS. Selecione TCP/TLS em Settings -> Configuration for SYSLOG.
* Habilite a implantação do gráfico de leme do monitor {product-name} a partir do Rancher Manager.
* Remova o limite superior do domínio de nível superior no validador de URL para varredura de registro.
* Verificar as dependências da Golang, incluindo verificações em tempo de execução.
* Suporte à verificação de vulnerabilidade do Debian 12 (Bookworm).
* Adicionar exportação CSV para Registry / Details para exportar CVEs para todas as imagens no registro configurado em Assets -> Registries para um registro selecionado.
* Permitir que o site {product-name} defina vários certificados ADFS em paralelo no campo de certificado x.509.
* Adicione e exiba o campo de comentário para as Regras de resposta.
* Especifique o que o {product-name} considera como contêineres do sistema por meio de uma variável de ambiente. Por exemplo, para o Rancher e namespaces padrão: NV_SYSTEM_GROUPS=*cattle-system;default
* Adicionar suporte para Kubernetes 1.27 e OpenShift 4.12

==== Correções de bugs

* Reduzir a repetição de registros nos registros do executor/controlador.
* A página de vários clusters não é renderizada.
* A remoção automática de grupos vazios leva 2 horas para ser excluída, em vez de 1 hora, de acordo com a programação.
* A regra de rede permitida manualmente não está sendo aplicada e resulta em violação da imagem de pausa.
* Bloqueio de conexões SSL mesmo que uma regra de rede permita o tráfego sob determinadas condições iniciais.
* Aviso de eventos de segurança mesmo com regras de rede permitidas devido a um problema de atualização de política na sincronização.
* Atividades de rede associando erroneamente o tráfego de grupo personalizado ao externo.
* O token da conta de serviço padrão do namespace montado em cada pod é muito privilegiado.
* Apesar de definir as regras de rede, as violações são registradas em eventos de segurança (falsos positivos) quando o contêiner é interrompido devido a um erro de falta de memória (OOM).
* Permitir que o usuário desative/ative a detecção e a proteção contra contêineres não gerenciados no cluster. Isso pode ser definido por meio da CLI do Manager:

[,shell]
----
set system detect_unmanaged_wl status -h
Usage: cli set system detect_unmanaged_wl status [OPTIONS] {true|false}

  Enable/disable detect unmanaged container
----

==== Outros

* Adicionar a configuração "leastPrivilege" no gráfico do Helm. Adicionar opção de timão para New_Service_Profile_Baseline. Uma nova versão do Helm chart (core) foi publicada para a versão 5.2.
* Habilite as configurações de integração do AWS Marketplace (adaptador de cobrança) no Helm chart.
* Atualize o configmap para oferecer suporte a novos recursos (vários certificados ADFS, desvio zero, New_Service_Profile_Baseline, SYSLOG TLS, tempo limite do usuário)
* Atualize as versões compatíveis do Kubernetes para 1.19+ e OpenShift 4.6+ (1.19+ com CRI-O)

=== 5.1.3 Maio de 2023

==== Aprimoramentos

* Adicione um novo feed de vulnerabilidades para a varredura da estrutura Microsoft .NET.
* As estatísticas do Enforcer são desativadas por padrão no exportador do Prometheus para melhorar a escalabilidade.
* Melhoria da usabilidade: Usar o scanner para digitalizar uma única imagem e imprimir o resultado (veja o exemplo abaixo).
* Adicione a verificação imagePullPolicy nos critérios das regras de controle de admissão.
* Mostrar mensagem de aviso quando o esquema CRD estiver desatualizado.

==== Correções de bugs

* A tela Atividade de rede não é renderizada ou é renderizada incorretamente.
* A remoção automática de grupos vazios leva 2 horas para ser excluída, em vez de 1 hora, de acordo com a programação.
* O perfil de conformidade não é exibido no console da interface do usuário.
* Filtro avançado em eventos de segurança com nível de "erro" ausente.
* A senha salva com caractere especial falha em uma tentativa futura de autenticação.
* A página de vários clusters não é renderizada corretamente quando as solicitações são altas.
* O painel de detalhes do registro (inferior) não está sendo atualizado.

==== Saída de amostra do scanner

[,shell]
----
Image: https://registry.hub.docker.comlibrary/alpine:3.4
Base OS: alpine:3.4.6
TOTAL: 6, HIGH: 1, MEDIUM: 5, LOW: 0, UNKNOWN: 0
┌─────────┬───────────────┬──────────┬───────────┬───────────────┬────────────┐
│ PACKAGE │ VULNERABILITY │ SEVERITY │ VERSION   │ FIXED VERSION │ PUBLISHED  │
├─────────┼───────────────┼──────────┼───────────┼───────────────┼────────────┤
│ openssl │ CVE-2018-0732 │ High     │ 1.0.2n-r0 │ 1.0.2o-r1     │ 2018-06-12 │
│         ├───────────────┼──────────┤           ├───────────────┼────────────┤
│         │ CVE-2018-0733 │ Medium   │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0734 │          │           │ 1.0.2q-r0     │ 2018-10-30 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0737 │          │           │ 1.0.2o-r2     │ 2018-04-16 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-0739 │          │           │ 1.0.2o-r0     │ 2018-03-27 │
│         ├───────────────┤          │           ├───────────────┼────────────┤
│         │ CVE-2018-5407 │          │           │ 1.0.2q-r0     │ 2018-11-15 │
└─────────┴───────────────┴──────────┴───────────┴───────────────┴────────────┘
----

=== 5.1.2 Março de 2023

==== Aprimoramentos

* Suporte a grupo de endereços baseado em host virtual e proteções de rede correspondentes a políticas. Isso permite um caso de uso em que dois endereços FQDN diferentes são resolvidos para o mesmo endereço IP, mas devem ser aplicadas regras diferentes para cada FQDN. Um novo grupo personalizado com '`address=vh:xxx.yyy`' pode ser criado usando o indicador '`vh:`' para ativar essa proteção. Uma regra de rede pode então usar o grupo personalizado como a fonte '`From`' com base no nome do host virtual (em vez do endereço IP resolvido) para impor regras diferentes para hosts virtuais.
* Lista de contêineres de conformidade para excluir os contêineres encerrados.
* Aprimore as regras de DLP para oferecer suporte a curingas simples no padrão.
* Adicionar suporte ao cri-o 1.26+ e ao OpenShift 4.11+.
* Tornar o gravatar opcional.
* Exibir recurso de namespace de cluster no console/UI.
* Exibir a gravidade/classificação da fonte (por exemplo, Red Hat, Ubuntu...) juntamente com a pontuação de gravidade do NVD no console.
* Não permita a desativação de SSO/RBAC para Rancher e OpenShift se o usuário estiver autenticado por meio de SSO.
* Adicione a ativação da varredura automática e a exclusão do envelhecimento de grupos não utilizados ao configMap.
* Incluir endereço IP de origem/destino externo em csv/pdf para violações de negação implícita
* Várias otimizações de desempenho e dimensionamento para uso de CPU e memória do controlador e do executor.

==== Correções de bugs

* Correção da lentidão do aplicativo nos nós do COS (Container Optimized OS) do GKE quando no modo Protect.
* SUSE Linux (SLES) 15.4 CVE não correspondente no scanner. Com essa correção, se a gravidade for fornecida no feed, a vulnerabilidade será adicionada ao banco de dados, mesmo que o registro NVD esteja ausente. É possível que o relatório inclua vulnerabilidades sem pontuações CVE.

==== Outros

* Aprimorar as opções de CRD de controle de admissão no helm https://github.com/neuvector/neuvector-helm/pull/237.
* Adicionar novas variáveis de ambiente do enforcer ao helm chart.

=== 5.1.1 Fevereiro de 2023

==== Aprimoramentos

* Adicione "`package`" como informação ao evento syslog para uma vulnerabilidade detectada.
* Adicione a variável de ambiente do Enforcer ENF_NETPOLICY_PULL_INTERVAL - valor em segundos (valor recomendado 60) para reduzir o tráfego de rede e o consumo de recursos resultante pelo Enforcer devido a atualizações/recalculações de políticas. (Observação: essa foi uma adição não documentada até agosto de 2023).

[,yaml]
----
           - name: ENF_NETPOLICY_PULL_INTERVAL
             value: "60"   <== regulate the pulling gap by 60 seconds
----

==== Correções de bugs

* Erros de exclusão de grupo vazio "Objeto não encontrado"
* Alerta/bloqueio de tráfego dentro do mesmo contêiner
* Violações implícitas inesperadas para o tráfego de saída do istio com a regra de permissão em vigor
* Ao fazer upgrade da versão {product-name} 4.x, a associação incorreta ao grupo de pods causa uma violação inesperada da política
* Falha na autenticação do OIDC com o ADFS quando caracteres de codificação adicionais aparecem na solicitação
* Alto uso de memória pelo dp criando e excluindo pods
* Atualize o alpine para corrigir vários CVEs, incluindo o Manager: CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552
* Correção de vários bugs da interface do usuário

==== Outros

* Gráfico do leme atualizado para permitir a substituição do certificado para comunicações internas

=== 5.1.0 Dezembro de 2022

==== Aprimoramentos

* Banco de dados de varredura (CVE) centralizado e com vários clusters. O cluster primário (mestre) pode verificar um registro/repo designado como um registro federado. Os resultados da varredura desses registros serão sincronizados com todos os clusters gerenciados (remotos). Isso permite a exibição dos resultados da varredura no console do cluster gerenciado, bem como o uso dos resultados nas regras de controle de admissão do cluster gerenciado. Os registros só precisam ser verificados uma vez, em vez de serem verificados por cada cluster, reduzindo o uso da CPU/memória e da largura de banda da rede.
* Aprimorar as regras de controle de admissão:
 ** Critérios personalizados para regras de controle de admissão. Permita que os usuários definam critérios de recursos em todos os campos relacionados a pods e que sejam usados em regras, por exemplo, item.metadata.annotationsKey contém 'neuvector', item.metadata.name='xyzzy' etc.
 ** Adicionar critérios para verificar se há configurações RBAC de alto risco para contas de serviço ao implantar pods. Isso inclui os critérios "qualquer ação de recursos de carga de trabalho", "qualquer ação no RBAC", "criar recursos de carga de trabalho", "listar segredos" e "executar em um contêiner".
 ** Adicionar comparação de versão semântica aos módulos para regras de controle de admissão. Isso permite que operadores > ou < sejam aplicados a números de versão em regras (por exemplo, não permitir que o módulo curl<6.2.0 seja implantado). Isso permite verificações específicas de versão nos pacotes instalados.
 ** Adicione uma regra de controle de admissão para Admissão de segurança de pod (PSA) compatível com o Kubernetes 1.25+.
* Adicione a nova variável de ambiente NO_DEFAULT_ADMIN que, quando ativada, não cria um usuário "admin". Isso é usado para a integração do SSO do Rancher como padrão. Se não estiver ativado, avisa persistentemente o usuário e registra eventos para alterar a senha padrão do administrador se ela não for alterada do padrão.
* O bloqueio do login após tentativas fracassadas de login agora é o padrão. O valor padrão é 5 tentativas e pode ser configurado em Settings -> Users & Roles-> Password Profile.
* Adicionar nova variável de ambiente para ajuste de desempenho ENF_NO_SYSTEM_PROFILES, valor: "1". Quando ativado, ele desativará os monitores de processos e arquivos. Nenhum processo de aprendizagem, nenhum modo de perfil, nenhum incidente de processo/arquivo (pacote) e nenhum monitor de atividade de arquivo serão executados. Isso reduzirá o uso de recursos de CPU/memória e as operações de arquivo.
* Adicione uma configuração de dimensionamento automático personalizado para pods de scanner, com valores Atrasado, Imediato e Desativado. Importante: O dimensionamento automático do scanner não é suportado quando o scanner é implantado com um operador do OpenShift, pois o operador sempre alterará o número de pods para o valor configurado.
 ** *_Estratégia atrasada:_*
  *** Quando o controlador principal vê continuamente "task count" > 0 por > 90 segundos, um novo pod de scanner é iniciado se o maxScannerPods ainda não tiver sido atingido
  *** Quando o controlador principal vê continuamente que a "contagem de tarefas" é 0 por mais de 180 segundos, ele reduz um pod de scanner se o minScannerPods ainda não tiver sido atingido
 ** *_Estratégia imediata:_*
  *** Toda vez que o controlador principal vê "task count" > 0, um novo pod de scanner é iniciado se o maxScannerPods ainda não tiver sido atingido
  *** Quando o controlador principal vê continuamente que a "contagem de tarefas" é 0 por mais de 180 segundos, ele reduz um pod de scanner se o minScannerPods ainda não tiver sido atingido
* Os grupos personalizados agora podem usar rótulos de namespace, incluindo os rótulos de namespace do Rancher. Em geral, os rótulos de pod e namespace agora podem ser adicionados aos grupos personalizados.
* Adicionar a capacidade de ocultar namespaces e grupos selecionados na exibição Network Activity.
* Suporte total para o Cilium cni.
* Suporte total ao OpenShift 4.9 e 4.10.
* As ferramentas de compilação agora estão disponíveis para o projeto {product-name}/Open Zero Trust (OZT) em https://github.com/openzerotrust/openzerotrust.io.
* {product-name} agora lista a ID da versão e o resumo SHA256 de cada versão do controlador, do gerenciador e do executor em https://github.com/neuvector/manifests/tree/main/versions.
* Os dados de telemetria anônimos (número de nós, grupos, regras) agora são informados a um serviço de nuvem do Rancher após a implantação para ajudar a equipe do projeto a entender o comportamento de uso. Isso pode ser desativado (opt-out) na interface do usuário ou com configMap (No_Telemetry_Report) ou API REST.
* (Adendo de janeiro de 2023). Suporte à política de rede baseada em ServiceEntry com o Istio. A funcionalidade de aplicação da política de rede de saída foi adicionada na versão 5.1.0 para pods para destinos ServiceEntry declarados com o Istio. Normalmente, um ServiceEntry define como um serviço externo referido pelo nome DNS é resolvido para um IP de destino. Antes da versão 5.1, o site {product-name} não conseguia detectar e aplicar regras para conexões a um ServiceEntry, portanto, todas as conexões eram classificadas como externas. Com a versão 5.1, as regras podem ser aplicadas a destinos específicos de ServiceEntry. IMPORTANTE: Se você estiver atualizando para a versão 5.1 com uma implantação baseada no Istio, novas regras deverão ser criadas para permitir essas conexões e evitar alertas de violação. Após a atualização, as violações implícitas serão relatadas para o tráfego recém-visível se não existirem regras de permissão. Novas regras de tráfego podem ser aprendidas e criadas automaticamente no modo Discover. Para permitir esse tráfego, você pode colocar o grupo no modo de descoberta ou criar um grupo personalizado com endereços (ou nome DNS) e uma nova regra de rede para esse destino para permitir o tráfego. OBSERVAÇÃO: Há um erro na versão 5.1.0 no destino relatado pelas violações de negação que não representam o destino correto.  O bug relata que tanto o nome do servidor quanto o nome do cliente são os mesmos.  Esse problema será resolvido em uma próxima versão do patch.

==== Correções de bugs

* Reduzir o consumo de memória do controlador de dados de benchmark cis desnecessários criados durante atualizações contínuas. Esse problema não ocorre em novas implementações.
* Remova a licença da tela de configuração (não é mais necessária).

=== 5.0.6-s1 Março de 2023

==== Correções de bugs

* Atualize os pacotes alpine para corrigir os CVEs no curl, incluindo CVE-2023-23914, CVE-2023-23915 e CVE-2023-23916

=== 5.0.6 Fevereiro de 2023

==== Correções de bugs

* Alto uso de memória em dpMsgConnection
* Alto uso de memória no processo dp no enforcer se houver muitas regras de política aprendidas com carga de trabalho não gerenciada (vazamento de memória)
* O tcpdump não consegue iniciar com êxito ao detectar um tráfego no contêiner
* Atualize o alpine para corrigir vários CVEs, incluindo o Manager: CVE-2022-37454, CVE-2022-42919, CVE-2022-45061, CVE-2021-46848; Enforcer: CVE-2022-43551, CVE-2022-43552

=== 5.0.5 Novembro de 2022

==== Correções de bugs

* A atualização para a versão 5.0.x resulta em uma mensagem de erro sobre o Manager, o Controller e o Enforcer executando versões diferentes.
* Os agentes de aplicação da lei entram em pânico rotineiro, o que resulta em uma morte por PD.  A WebUI não reflete o enforcer como on-line.
* Incidente inesperado de Process.Profile.Violation no grupo NV.Protect em qual comando no coreos.

=== 5.0.4 Outubro de 2022

==== Atualizações de segurança

* Atualize o alpine para remover o CVE-2022-40674 crítico na biblioteca expat do gerenciador, bem como outros CVEs menores.

==== Aprimoramentos

* Adicionar suporte ao Antrea CNI

==== Correções de bugs

* Correção de incidente inesperado de process.profile.violation no grupo NV.Protect.
* Quando o SSL está desativado no acesso à interface do usuário do gerenciador, a senha do usuário é impressa no registro do gerenciador.

=== 5.0.3 September, 2022

==== Aprimoramentos

* Não exibir o EULA após a reinicialização bem-sucedida do volume persistente.
* Use o filtro de imagem na configuração do perfil de vulnerabilidade para ignorar os resultados da varredura de contêineres.
* Suporte ao scanner em ações do GitHub em https://github.com/neuvector/neuvector-image-scan-action.
* Adicionar variáveis de ambiente do Enforcer para desativar a varredura de segredos e executar benchmarks do CIS

[,yaml]
----
    env:
      - name: ENF_NO_SECRET_SCANS  (available after v4.4.4)
        value: "1"
      - name: ENF_NO_AUTO_BENCHMARK (after v5.0.3)
        value: "1"
----

==== Correções de bugs

* O Enforcer não consegue iniciar ocasionalmente.
* Vazamento de conexão em ambientes de federação com vários clusters.
* A página de conformidade não está carregando algumas vezes em Riscos de segurança -> Compliance

=== 5.0.2 Julho de 2022

==== Aprimoramentos

* Há suporte para clusters endurecidos do Rancher e do SELinux.

==== Correções de bugs

* Alta utilização da CPU do processo do agente em sistemas k3s.
* Os grupos LDAP do AD não estão funcionando corretamente após a atualização para a versão 5.0.
* O Enforcer continua reiniciando devido ao erro = muitos arquivos abertos (rke2/cilium).
* Não foi possível fazer o download do registro de suporte com êxito.

=== 5.0.1 Junho de 2022

==== Aprimoramentos

* Suporte à verificação de vulnerabilidade do openSUSE Leap OS (na imagem do scanner).
* Scanner: implementar atributos de eliminação durante a reconstrução do repositório de imagens.
* Verifique a implementação do {product-name} e o suporte para hosts habilitados para SELinux. Veja abaixo os detalhes sobre a aplicação provisória de patches até que o mapa do leme seja atualizado.
* Distinguir entre o gráfico de recursos e os gráficos de parceiros na interface do usuário do Rancher com mais destaque. Adicionar/atualizar ingress.kubernetes.io/protocol: https a nginx.ingress.kubernetes.io/backend-protocol: "HTTPS".
* O OpenShift Operator atual oferece suporte a rotas de passagem para serviços de API e federação. Parâmetros adicionais do Helm Value foram adicionados para dar suporte aos tipos de terminação de rota de borda e recriptografia.

==== Correções de bugs

* O cluster AKS pode adicionar uma chave inesperada no webhook de controle de admissão.
* O Enforcer não está se tornando operacional no cluster k8s 1.24 com tempo de execução do containerd 1.64. Separadamente, o enforcer às vezes falha ao iniciar.
* Qualquer usuário com função de administrador (usuário local ou SSO) que promova um cluster para fed master deve ser promovido automaticamente para a função fedAdmin.
* Quando também se usa o administrador padrão do Rancher em {product-name} no cluster mestre, a função de login {product-name} é admin, não fedAdmin.
* Correção de várias falhas de goroutine.
* Violação implícita do IP do host não associado ao nó.
* O ComplianceProfile não mostra a tag PCI.
* O mapeamento de grupos LDAP às vezes não é mostrado.
* A ferramenta Risk Review and Improvement resultará na mensagem de erro "Failed to update system config" (Falha ao atualizar a configuração do sistema): Solicitação em formato incorreto".
* OKD 3.11 - O erro do clusterrole é exibido mesmo que ele exista.

==== Correções de CVE

* Alta CVE-2022-29458 encontrada no pacote ncurses em todas as imagens.
* CVE-2022-27778 e CVE-2022-27782 elevados encontrados no pacote curl na imagem do Updater.

==== Detalhes sobre o suporte ao SELinux

{product-name} não precisa de nenhuma configuração adicional para que os clusters habilitados para SELinux sejam implantados e funcionem. Implementação testada do {product-name} em um cluster reforçado RKE2 com base no SELinux do RHEL 8.5. O {product-name} foi implementado com êxito se o PSP estiver ativado e a implementação do gerenciador de patches e do scanner. A próxima versão do gráfico deve corrigir o problema abaixo.

Exemplo anexado de ativação do psp a partir do gráfico do Rancher e comandos fornecidos abaixo para aplicação de patches no Manager e no Scanner. O ID do usuário no comando patch pode ser qualquer número.

[,shell]
----
kubectl patch deploy -ncattle-neuvector-system neuvector-scanner-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
kubectl patch deploy -ncattle-neuvector-system neuvector-manager-pod --patch '{"spec":{"template":{"spec":{"securityContext":{"runAsUser": 5400}}}}}'
----

Exemplo de ativação do PSP:

[,shell]
----
[neuvector@localhost nv]$ getenforce
Enforcing
[neuvector@localhost nv]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

[neuvector@localhost nv]$ kk get psp
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME                      PRIV    CAPS                                      SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
global-restricted-psp     false                                             RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
neuvector-binding-psp     true    SYS_ADMIN,NET_ADMIN,SYS_PTRACE,IPC_LOCK   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
system-unrestricted-psp   true    *                                         RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
[neuvector@localhost nv]$ nvpo.sh
NAME                                        READY   STATUS    RESTARTS   AGE     IP           NODE                    NOMINATED NODE   READINESS GATES
neuvector-controller-pod-54f69f7f9c-6h822   1/1     Running   0          5m51s   10.42.0.29   localhost.localdomain   <none>           <none>
neuvector-enforcer-pod-jz77b                1/1     Running   0          5m51s   10.42.0.30   localhost.localdomain   <none>           <none>
neuvector-manager-pod-588488bb78-p6vf9      1/1     Running   0          111s    10.42.0.32   localhost.localdomain   <none>           <none>
neuvector-scanner-pod-87474dcff-s8vgt       1/1     Running   0          114s    10.42.0.31   localhost.localdomain   <none>           <none>
----

=== 5.0.0 Versão de disponibilidade geral (GA) Maio de 2022

==== Aprimoramentos

* Promoção automatizada de modos de grupo. Promove o modo de proteção de um grupo com base no tempo decorrido e nos critérios. Não se aplica a grupos criados por CRD. Esse recurso permite que um novo aplicativo seja executado no modo Discover por algum tempo, aprendendo o comportamento e {product-name} criando regras de lista de permissões para Rede e Processo e, em seguida, passando automaticamente para o modo Monitor e, depois, para o modo Protect. Descobrir para monitorar o critério: Tempo decorrido para aprender toda a atividade de rede e processo de pelo menos um pod ativo no Grupo. Critério Monitorar para Proteger: Não há eventos de segurança (rede, processo etc.) para o período definido para o Grupo.
* Suporte para aplicativos Rancher 2.6.5 e gráfico do Marketplace. Faz a implantação no namespace cattle-neuvector-system e habilita o SSO do Rancher para {product-name}. Observação: As implantações anteriores do Rancher (por exemplo, gráficos do catálogo de parceiros, versão 1.9.x e anteriores) devem ser completamente removidas para que seja possível atualizar para o novo gráfico.
* Suporte à varredura do SUSE Linux (SLE, SLES) e do Microsoft Mariner
* Processo de desvio zero e proteção de arquivos. Esse é o novo modo padrão para proteções de processos e arquivos. O Zero-drift permite automaticamente apenas processos originados do processo pai que está na imagem original do contêiner e não permite a instalação de atualizações de arquivos ou de novos arquivos. Quando estiver no modo Discover ou Monitor, o zero-drift alertará sobre qualquer processo suspeito ou atividade de arquivo. No modo Protect, ele bloqueará essa atividade. O Zero-drift não exige que os processos sejam aprendidos ou adicionados a uma lista de permissões. A desativação do zero-drift para um grupo fará com que as regras de processo e arquivo listadas para o grupo entrem em vigor.
* Proteção de modo de política dividida para rede, processo/arquivo. Agora há uma configuração global disponível em Settings -> Configuration para definir separadamente o modo de proteção de rede para a aplicação de regras de rede. A ativação dessa opção (o padrão é desativado) faz com que todas as regras de rede estejam no modo de proteção selecionado (Descobrir, Monitorar, Proteger), enquanto as regras de processo/arquivo permanecem no modo de proteção desse grupo, conforme exibido na tela Policy -> Groups. Dessa forma, as regras de rede podem ser definidas como Protect (bloqueio), enquanto a política de processo/arquivo pode ser definida como Monitor, ou vice-versa.
* Detecção de regras WAF, regras DLP aprimoradas (cabeçalho, URL, pacote completo). Usado para conexões de entrada com pods de aplicativos da Web, bem como para conexões de saída com serviços de API para reforçar a segurança da API.
* CRD para WAF, DLP e controles de admissão. OBSERVAÇÃO: são necessárias permissões/vinculações de função de cluster adicionais. Consulte as seções de implantação do Kubernetes e do OpenShift. Importação/exportação de CRD e controle de versão para controles de admissão suportados pelo CRD.
* Integração do SSO do Rancher para iniciar o console {product-name} por meio do Rancher Manager. Esse recurso só estará disponível se os contêineres {product-name} forem implantados por meio do Rancher. Essa implantação é extraída do repositório espelhado do Rancher (por exemplo, rancher/mirrored-neuvector-controller:5.0.0) e implantada no namespace cattle-neuvector-system. OBSERVAÇÃO: Requer a versão atualizada do Rancher 2.6.5 de maio de 2022 ou posterior, e somente as funções de administrador e proprietário do cluster são compatíveis no momento.
* Oferece suporte à implementação no RKE2.
* Suporte à Federação de clusters (gerenciador de vários clusters) por meio de um proxy. Configure o proxy em Settings -> Configuration e ative o proxy ao configurar as conexões de federação.
* Monitore as ligações/role de cluster do rbac necessárias e alerte em eventos e na interface do usuário se alguma estiver faltando.
* Critérios de suporte de limitações de recursos nas regras de controle de admissão.
* Suporte ao formato Microsoft Teams para webhooks.
* Suporte a grupos aninhados AD/LDAP sob o grupo de funções mapeado.
* Suporte a clusterrolebindings ou rolebindings com informações de grupo no IDP para Openshift.
* Permitir que as regras de rede e as regras de controle de admissão sejam promovidas a uma regra federada.

==== Correções de bugs

* Corrigir o problema do backup da função de federação de trabalhadores que deve ser restaurado em clusters não federados.
* Melhore o tempo de carregamento da página para um grande número de CVEs em Riscos de segurança -> Vulnerabilidades
* Permitir que o usuário alterne o modo quando selecionar todos os grupos no menu Policy -> Groups. Avisar se o grupo Nodes também estiver selecionado.
* Recolha os itens de verificação de conformidade com o mesmo nome e torne-os expansíveis.
* Aumentar a segurança das comunicações gRPC.
* Corrigido: não é possível obter informações corretas sobre a carga de trabalho privilegiada na configuração do rke2.
* Correção do problema com o suporte do openSUSE Leap 15.3 (k8s/crio).

==== Outras atualizações

* Atualização do gráfico do leme appVersion para 5.0.0 e versão do gráfico para 2.2.0
* Removido o recurso/menu de varredura sem servidor.
* Removido o suporte para a integração do resultado da verificação do Jfrog Xray (a verificação do registro do Artifactory ainda é suportada).
* O suporte para implementação no ECS não é mais fornecido. O allinone ainda deve poder ser implantado no ECS, mas a documentação das etapas e configurações não é mais suportada.

=== Atualização de {product-name} 4.x para 5.x (anterior a 5.2.x)

[NOTE]
====
As instruções abaixo se aplicam aos upgrades para as versões 5.0.x e 5.1.x. Para a versão 5.2.x, as contas de serviço e as associações foram alteradas e devem ser xref:kubernetes.adoc#_deploy_suse_security[revisadas] para planejar as atualizações.
====


Para usuários do Helm, atualize para {product-name} Helm chart 2.0.0 ou posterior. Se estiver atualizando uma instalação do Operator ou do Helm no OpenShift, consulte a observação abaixo.

. Excluir o antigo clusterrole de neuvector-binding-customresourcedefinition

[,shell]
----
kubectl delete clusterrole neuvector-binding-customresourcedefinition
----

. Aplicar novo verbo de atualização para neuvector-binding-customresourcedefinition clusterrole

[,shell]
----
kubectl create clusterrole neuvector-binding-customresourcedefinition --verb=watch,create,get,update --resource=customresourcedefinitions
----

. Excluir o esquema crd antigo para o Kubernetes 1.19+

[,shell]
----
kubectl delete -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/crd-k8s-1.19.yaml
----

. Criar um novo esquema crd para o Kubernetes 1.19+

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/waf-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/dlp-crd-k8s-1.19.yaml
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.0.0/admission-crd-k8s-1.19.yaml
----

. Criar uma nova função de cluster de Admissão, DLP e WAF e uma vinculação de função de cluster

[,shell]
----
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----

. Atualizar nomes e caminhos de imagens para extrair imagens {product-name} do hub do Docker (docker.io), por exemplo.

* neuvector/manager:5.0.0
* neuvector/controller:5.0.0
* neuvector/enforcer:5.0.0
* neuvector/scanner:latest
* neuvector/updater:latest

Opcionalmente, remova todas as referências à licença {product-name} e ao segredo do registro nos gráficos do Helm, yaml de implantação, configmap, scripts etc., pois eles não são mais necessários para extrair as imagens ou para começar a usar o {product-name}.

*Observação sobre SCC e atualização via Operator/Helm*

O Privileged SCC é adicionado à conta de serviço especificada no yaml de implementação pelo Operator versão 1.3.4 e superior em novas implementações. No caso de upgrade do Operador {product-name} de uma versão anterior para a 1.3.4 ou do Helm para a 2.0.0, exclua o Privileged SCC antes de fazer o upgrade.

[,shell]
----
oc delete rolebinding -n neuvector system:openshift:scc:privileged
----

==== Versão Beta 1 lançada em abril de 2022

* Recurso completo, incluindo promoção automatizada de modos de grupo. Promove o modo de proteção de um grupo com base no tempo decorrido e nos critérios. Não se aplica a grupos criados por CRD. Esse recurso permite que um novo aplicativo seja executado no modo Discover por algum tempo, aprendendo o comportamento e {product-name} criando regras de lista de permissões para Rede e Processo e, em seguida, passando automaticamente para o modo Monitor e, depois, para o modo Protect. Descobrir para monitorar o critério: Tempo decorrido para aprender toda a atividade de rede e processo de pelo menos um pod ativo no Grupo. Critério Monitorar para Proteger: Não há eventos de segurança (rede, processo etc.) para o período definido para o Grupo.
* Suporte para aplicativos Rancher 2.6.5 e gráfico do Marketplace. Faz a implantação no namespace cattle-neuvector-system e habilita o SSO do Rancher para {product-name}. Observação: As implantações anteriores do Rancher (por exemplo, gráficos do catálogo de parceiros, versão 1.9.x e anteriores) devem ser completamente removidas para que seja possível atualizar para o novo gráfico.
* Tags para Enforcer, Manager, Controller: 5.0.0-b1 (por exemplo, neuvector/controller:5.0.0-b1)

==== Versão Preview.3 lançada em março de 2022

[CAUTION]
.importante
====

Para atualizar as implementações de visualização anteriores para os novos recursos CRD WAF, DLP e controle de admissão, atualize o CRD yaml e adicione novas ligações rbac/role:

[,shell]
----
kubectl apply -f https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/latest/crd-k8s-1.19.yaml
kubectl create clusterrole neuvector-binding-nvwafsecurityrules --verb=list,delete --resource=nvwafsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvwafsecurityrules --clusterrole=neuvector-binding-nvwafsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvadmissioncontrolsecurityrules --verb=list,delete --resource=nvadmissioncontrolsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvadmissioncontrolsecurityrules --clusterrole=neuvector-binding-nvadmissioncontrolsecurityrules --serviceaccount=neuvector:default
kubectl create clusterrole neuvector-binding-nvdlpsecurityrules --verb=list,delete --resource=nvdlpsecurityrules
kubectl create clusterrolebinding neuvector-binding-nvdlpsecurityrules --clusterrole=neuvector-binding-nvdlpsecurityrules --serviceaccount=neuvector:default
----
====


==== Aprimoramentos

* Suporte à varredura do SUSE Linux (SLE, SLES) e do Microsoft Mariner
* Processo de desvio zero e proteção de arquivos. Esse é o novo modo padrão para proteções de processos e arquivos. O Zero-drift permite automaticamente apenas processos originados do processo pai que está na imagem original do contêiner e não permite a instalação de atualizações de arquivos ou de novos arquivos. Quando estiver no modo Discover ou Monitor, o zero-drift alertará sobre qualquer processo suspeito ou atividade de arquivo. No modo Protect, ele bloqueará essa atividade. O Zero-drift não exige que os processos sejam aprendidos ou adicionados a uma lista de permissões. A desativação do zero-drift para um grupo fará com que as regras de processo e arquivo listadas para o grupo entrem em vigor.
* Proteção de modo de política dividida para rede, processo/arquivo. Agora há uma configuração global disponível em Settings -> Configuration para definir separadamente o modo de proteção de rede para a aplicação de regras de rede. A ativação dessa opção (o padrão é desativado) faz com que todas as regras de rede estejam no modo de proteção selecionado (Descobrir, Monitorar, Proteger), enquanto as regras de processo/arquivo permanecem no modo de proteção desse grupo, conforme exibido na tela Policy -> Groups. Dessa forma, as regras de rede podem ser definidas como Protect (bloqueio), enquanto a política de processo/arquivo pode ser definida como Monitor, ou vice-versa.
* Detecção de regras WAF, regras DLP aprimoradas (cabeçalho, URL, pacote completo)
* CRD para WAF, DLP e controles de admissão. OBSERVAÇÃO: são necessárias permissões/vinculações de função de cluster adicionais. Consulte as seções de implantação do Kubernetes e do OpenShift. Importação/exportação de CRD e controle de versão para controles de admissão suportados pelo CRD.
* Integração do SSO do Rancher para iniciar o console {product-name} por meio do Rancher Manager. Esse recurso só estará disponível se os contêineres {product-name} forem implantados por meio do Rancher. OBSERVAÇÃO: Requer a versão atualizada do Rancher (data/versão a ser definida).
* Oferece suporte à implementação no RKE2.
* Suporte à Federação de clusters (gerenciador de vários clusters) por meio de um proxy.
* Monitore as ligações/role de cluster do rbac necessárias e alerte em eventos e na interface do usuário se alguma estiver faltando.
* Critérios de suporte de limitações de recursos nas regras de controle de admissão.

==== Correções de bugs

* Corrigir o problema do backup da função de federação de trabalhadores que deve ser restaurado em clusters não federados.

==== Versão Preview.2 lançada em fevereiro de 2022

* Pequenas alterações de arquivo e licença no código-fonte, sem adição de recursos.

==== Suporte para implementação no AWS ECS Prejudicado

O suporte para implementação no ECS não é mais fornecido. O allinone ainda deve poder ser implantado no ECS, mas a documentação das etapas e configurações não é mais suportada.

=== 5.0 'Tech Preview' Janeiro de 2022

==== Aprimoramentos

* Primeiro lançamento de uma versão "tech-preview", sem suporte, da versão de código aberto {product-name} 5.0.
* Adicione suporte às regras OWASP Top-10, do tipo WAF, para detectar ataques de rede em cabeçalhos ou no corpo. Inclui suporte às definições de assinaturas do CRD e aplicação aos grupos apropriados.
* Remove os recursos de varredura sem servidor.

==== Correções de bugs

* TBD

==== Outros

* O Helm chart v1.8.9 foi publicado para implantações 5.0.0. Se estiver usando isso com a versão prévia do 5.0.0, as seguintes alterações deverão ser feitas no values.yml:
 ** Atualize o registro para docker.io
 ** Atualizar nomes/tags de imagens para a versão de visualização no Docker hub
 ** Deixe o imagePullSecrets vazio
